export interface ShortcutItem {
  id: string
  app: string
  category: string
  title: string
  description: string
  keys: string
  platform?: string
}

export const shortcutsData: ShortcutItem[] = [
  // MS WORD - 100+ shortcuts
  {
    id: "word-1",
    app: "MS Word",
    category: "File Operations",
    title: "Create New Document",
    description: "Opens a new blank document",
    keys: "Ctrl + N",
    platform: "Windows",
  },
  {
    id: "word-2",
    app: "MS Word",
    category: "File Operations",
    title: "Open Document",
    description: "Opens an existing document",
    keys: "Ctrl + O",
    platform: "Windows",
  },
  {
    id: "word-3",
    app: "MS Word",
    category: "File Operations",
    title: "Save Document",
    description: "Saves the current document",
    keys: "Ctrl + S",
    platform: "Windows",
  },
  {
    id: "word-4",
    app: "MS Word",
    category: "File Operations",
    title: "Save As",
    description: "Save document with new name",
    keys: "Ctrl + Shift + S",
    platform: "Windows",
  },
  {
    id: "word-5",
    app: "MS Word",
    category: "File Operations",
    title: "Print Document",
    description: "Opens print dialog",
    keys: "Ctrl + P",
    platform: "Windows",
  },
  {
    id: "word-6",
    app: "MS Word",
    category: "File Operations",
    title: "Close Document",
    description: "Closes current document",
    keys: "Ctrl + W",
    platform: "Windows",
  },
  {
    id: "word-7",
    app: "MS Word",
    category: "Editing",
    title: "Undo",
    description: "Reverses last action",
    keys: "Ctrl + Z",
    platform: "Windows",
  },
  {
    id: "word-8",
    app: "MS Word",
    category: "Editing",
    title: "Redo",
    description: "Redoes last undone action",
    keys: "Ctrl + Y",
    platform: "Windows",
  },
  {
    id: "word-9",
    app: "MS Word",
    category: "Editing",
    title: "Cut",
    description: "Cut selected text",
    keys: "Ctrl + X",
    platform: "Windows",
  },
  {
    id: "word-10",
    app: "MS Word",
    category: "Editing",
    title: "Copy",
    description: "Copy selected text",
    keys: "Ctrl + C",
    platform: "Windows",
  },
  {
    id: "word-11",
    app: "MS Word",
    category: "Editing",
    title: "Paste",
    description: "Paste clipboard content",
    keys: "Ctrl + V",
    platform: "Windows",
  },
  {
    id: "word-12",
    app: "MS Word",
    category: "Editing",
    title: "Paste Special",
    description: "Open paste special dialog",
    keys: "Ctrl + Alt + V",
    platform: "Windows",
  },
  {
    id: "word-13",
    app: "MS Word",
    category: "Editing",
    title: "Select All",
    description: "Selects all document content",
    keys: "Ctrl + A",
    platform: "Windows",
  },
  {
    id: "word-14",
    app: "MS Word",
    category: "Editing",
    title: "Find",
    description: "Opens find dialog",
    keys: "Ctrl + F",
    platform: "Windows",
  },
  {
    id: "word-15",
    app: "MS Word",
    category: "Editing",
    title: "Find and Replace",
    description: "Opens find and replace dialog",
    keys: "Ctrl + H",
    platform: "Windows",
  },
  {
    id: "word-16",
    app: "MS Word",
    category: "Formatting",
    title: "Bold",
    description: "Make text bold",
    keys: "Ctrl + B",
    platform: "Windows",
  },
  {
    id: "word-17",
    app: "MS Word",
    category: "Formatting",
    title: "Italic",
    description: "Make text italic",
    keys: "Ctrl + I",
    platform: "Windows",
  },
  {
    id: "word-18",
    app: "MS Word",
    category: "Formatting",
    title: "Underline",
    description: "Underline text",
    keys: "Ctrl + U",
    platform: "Windows",
  },
  {
    id: "word-19",
    app: "MS Word",
    category: "Formatting",
    title: "Double Underline",
    description: "Double underline text",
    keys: "Ctrl + Shift + D",
    platform: "Windows",
  },
  {
    id: "word-20",
    app: "MS Word",
    category: "Formatting",
    title: "Strikethrough",
    description: "Strike through text",
    keys: "Alt + Shift + 5",
    platform: "Windows",
  },
  {
    id: "word-21",
    app: "MS Word",
    category: "Formatting",
    title: "Subscript",
    description: "Make text subscript",
    keys: "Ctrl + =",
    platform: "Windows",
  },
  {
    id: "word-22",
    app: "MS Word",
    category: "Formatting",
    title: "Superscript",
    description: "Make text superscript",
    keys: "Ctrl + Shift + +",
    platform: "Windows",
  },
  {
    id: "word-23",
    app: "MS Word",
    category: "Formatting",
    title: "Increase Font Size",
    description: "Increase font size",
    keys: "Ctrl + ]",
    platform: "Windows",
  },
  {
    id: "word-24",
    app: "MS Word",
    category: "Formatting",
    title: "Decrease Font Size",
    description: "Decrease font size",
    keys: "Ctrl + [",
    platform: "Windows",
  },
  {
    id: "word-25",
    app: "MS Word",
    category: "Formatting",
    title: "Clear Formatting",
    description: "Remove all formatting",
    keys: "Ctrl + Spacebar",
    platform: "Windows",
  },
  {
    id: "word-26",
    app: "MS Word",
    category: "Formatting",
    title: "Left Align",
    description: "Align text to left",
    keys: "Ctrl + L",
    platform: "Windows",
  },
  {
    id: "word-27",
    app: "MS Word",
    category: "Formatting",
    title: "Center Align",
    description: "Center align text",
    keys: "Ctrl + E",
    platform: "Windows",
  },
  {
    id: "word-28",
    app: "MS Word",
    category: "Formatting",
    title: "Right Align",
    description: "Align text to right",
    keys: "Ctrl + R",
    platform: "Windows",
  },
  {
    id: "word-29",
    app: "MS Word",
    category: "Formatting",
    title: "Justify",
    description: "Justify text",
    keys: "Ctrl + J",
    platform: "Windows",
  },
  {
    id: "word-30",
    app: "MS Word",
    category: "Formatting",
    title: "Increase Indent",
    description: "Increase paragraph indent",
    keys: "Tab",
    platform: "Windows",
  },
  {
    id: "word-31",
    app: "MS Word",
    category: "Navigation",
    title: "Go to Beginning",
    description: "Move cursor to start of document",
    keys: "Ctrl + Home",
    platform: "Windows",
  },
  {
    id: "word-32",
    app: "MS Word",
    category: "Navigation",
    title: "Go to End",
    description: "Move cursor to end of document",
    keys: "Ctrl + End",
    platform: "Windows",
  },
  {
    id: "word-33",
    app: "MS Word",
    category: "Navigation",
    title: "Previous Page",
    description: "Go to previous page",
    keys: "Page Up",
    platform: "Windows",
  },
  {
    id: "word-34",
    app: "MS Word",
    category: "Navigation",
    title: "Next Page",
    description: "Go to next page",
    keys: "Page Down",
    platform: "Windows",
  },
  {
    id: "word-35",
    app: "MS Word",
    category: "Navigation",
    title: "Go To Page",
    description: "Jump to specific page",
    keys: "Ctrl + G",
    platform: "Windows",
  },
  {
    id: "word-36",
    app: "MS Word",
    category: "Tables",
    title: "Insert Table",
    description: "Insert a table",
    keys: "Ctrl + Alt + T",
    platform: "Windows",
  },
  {
    id: "word-37",
    app: "MS Word",
    category: "Tables",
    title: "Tab to Next Cell",
    description: "Move to next table cell",
    keys: "Tab",
    platform: "Windows",
  },
  {
    id: "word-38",
    app: "MS Word",
    category: "Tables",
    title: "Tab to Previous Cell",
    description: "Move to previous table cell",
    keys: "Shift + Tab",
    platform: "Windows",
  },
  {
    id: "word-39",
    app: "MS Word",
    category: "Lists",
    title: "Bullet List",
    description: "Create bullet list",
    keys: "Ctrl + Shift + L",
    platform: "Windows",
  },
  {
    id: "word-40",
    app: "MS Word",
    category: "Lists",
    title: "Numbered List",
    description: "Create numbered list",
    keys: "Ctrl + Shift + N",
    platform: "Windows",
  },
  {
    id: "word-41",
    app: "MS Word",
    category: "Styles",
    title: "Open Styles Pane",
    description: "Show styles panel",
    keys: "Ctrl + Alt + Shift + S",
    platform: "Windows",
  },
  {
    id: "word-42",
    app: "MS Word",
    category: "Styles",
    title: "Apply Heading 1",
    description: "Apply Heading 1 style",
    keys: "Ctrl + Alt + 1",
    platform: "Windows",
  },
  {
    id: "word-43",
    app: "MS Word",
    category: "Styles",
    title: "Apply Heading 2",
    description: "Apply Heading 2 style",
    keys: "Ctrl + Alt + 2",
    platform: "Windows",
  },
  {
    id: "word-44",
    app: "MS Word",
    category: "Styles",
    title: "Apply Heading 3",
    description: "Apply Heading 3 style",
    keys: "Ctrl + Alt + 3",
    platform: "Windows",
  },
  {
    id: "word-45",
    app: "MS Word",
    category: "Styles",
    title: "Apply Normal Style",
    description: "Apply Normal/Body style",
    keys: "Ctrl + Shift + N",
    platform: "Windows",
  },
  {
    id: "word-46",
    app: "MS Word",
    category: "References",
    title: "Insert Footnote",
    description: "Insert a footnote",
    keys: "Alt + Ctrl + F",
    platform: "Windows",
  },
  {
    id: "word-47",
    app: "MS Word",
    category: "References",
    title: "Insert Endnote",
    description: "Insert an endnote",
    keys: "Alt + Ctrl + D",
    platform: "Windows",
  },
  {
    id: "word-48",
    app: "MS Word",
    category: "References",
    title: "Insert Caption",
    description: "Insert caption for figure",
    keys: "Alt + Ctrl + L",
    platform: "Windows",
  },
  {
    id: "word-49",
    app: "MS Word",
    category: "View",
    title: "Print Layout",
    description: "Switch to Print Layout view",
    keys: "Ctrl + Alt + P",
    platform: "Windows",
  },
  {
    id: "word-50",
    app: "MS Word",
    category: "View",
    title: "Web Layout",
    description: "Switch to Web Layout view",
    keys: "Ctrl + Alt + W",
    platform: "Windows",
  },
  {
    id: "word-51",
    app: "MS Word",
    category: "View",
    title: "Outline View",
    description: "Switch to Outline view",
    keys: "Ctrl + Alt + O",
    platform: "Windows",
  },
  {
    id: "word-52",
    app: "MS Word",
    category: "View",
    title: "Draft View",
    description: "Switch to Draft view",
    keys: "Ctrl + Alt + N",
    platform: "Windows",
  },
  {
    id: "word-53",
    app: "MS Word",
    category: "Review",
    title: "Track Changes",
    description: "Toggle track changes",
    keys: "Ctrl + Shift + E",
    platform: "Windows",
  },
  {
    id: "word-54",
    app: "MS Word",
    category: "Review",
    title: "Accept All Changes",
    description: "Accept all tracked changes",
    keys: "Alt + Ctrl + A",
    platform: "Windows",
  },
  {
    id: "word-55",
    app: "MS Word",
    category: "Review",
    title: "Spelling Check",
    description: "Check spelling",
    keys: "F7",
    platform: "Windows",
  },
  {
    id: "word-56",
    app: "MS Word",
    category: "Symbols",
    title: "Insert Special Character",
    description: "Open symbol dialog",
    keys: "Alt + Ctrl + Shift + O",
    platform: "Windows",
  },
  {
    id: "word-57",
    app: "MS Word",
    category: "Symbols",
    title: "Insert Copyright",
    description: "Insert copyright symbol",
    keys: "Alt + Ctrl + C",
    platform: "Windows",
  },
  {
    id: "word-58",
    app: "MS Word",
    category: "Symbols",
    title: "Insert Trademark",
    description: "Insert trademark symbol",
    keys: "Alt + Ctrl + T",
    platform: "Windows",
  },
  {
    id: "word-59",
    app: "MS Word",
    category: "Symbols",
    title: "Insert Registered",
    description: "Insert registered symbol",
    keys: "Alt + Ctrl + R",
    platform: "Windows",
  },
  {
    id: "word-60",
    app: "MS Word",
    category: "Page Breaks",
    title: "Page Break",
    description: "Insert page break",
    keys: "Ctrl + Return",
    platform: "Windows",
  },
  {
    id: "word-61",
    app: "MS Word",
    category: "Page Breaks",
    title: "Column Break",
    description: "Insert column break",
    keys: "Ctrl + Shift + Return",
    platform: "Windows",
  },
  {
    id: "word-62",
    app: "MS Word",
    category: "Page Breaks",
    title: "Section Break",
    description: "Insert section break",
    keys: "Ctrl + Return",
    platform: "Windows",
  },
  {
    id: "word-63",
    app: "MS Word",
    category: "Headers/Footers",
    title: "Edit Header",
    description: "Edit document header",
    keys: "Alt + Shift + E",
    platform: "Windows",
  },
  {
    id: "word-64",
    app: "MS Word",
    category: "Headers/Footers",
    title: "Edit Footer",
    description: "Edit document footer",
    keys: "Alt + Shift + O",
    platform: "Windows",
  },
  {
    id: "word-65",
    app: "MS Word",
    category: "Case",
    title: "Change Case",
    description: "Open change case dialog",
    keys: "Shift + F3",
    platform: "Windows",
  },
  {
    id: "word-66",
    app: "MS Word",
    category: "Zoom",
    title: "Zoom In",
    description: "Increase zoom level",
    keys: "Ctrl + +",
    platform: "Windows",
  },
  {
    id: "word-67",
    app: "MS Word",
    category: "Zoom",
    title: "Zoom Out",
    description: "Decrease zoom level",
    keys: "Ctrl + -",
    platform: "Windows",
  },
  {
    id: "word-68",
    app: "MS Word",
    category: "Editing",
    title: "Go to Page Dialog",
    description: "Open go to page dialog",
    keys: "F5",
    platform: "Windows",
  },
  {
    id: "word-69",
    app: "MS Word",
    category: "Help",
    title: "Help",
    description: "Open help",
    keys: "F1",
    platform: "Windows",
  },
  {
    id: "word-70",
    app: "MS Word",
    category: "Comments",
    title: "Insert Comment",
    description: "Insert a new comment",
    keys: "Ctrl + Alt + M",
    platform: "Windows",
  },
  {
    id: "word-71",
    app: "MS Word",
    category: "Comments",
    title: "Delete Comment",
    description: "Delete selected comment",
    keys: "Ctrl + Alt + K",
    platform: "Windows",
  },
  {
    id: "word-72",
    app: "MS Word",
    category: "Selection",
    title: "Select Word",
    description: "Select current word",
    keys: "Ctrl + Shift + Right",
    platform: "Windows",
  },
  {
    id: "word-73",
    app: "MS Word",
    category: "Selection",
    title: "Select Sentence",
    description: "Select to end of sentence",
    keys: "Ctrl + Shift + Period",
    platform: "Windows",
  },
  {
    id: "word-74",
    app: "MS Word",
    category: "Selection",
    title: "Select Paragraph",
    description: "Select entire paragraph",
    keys: "Ctrl + Shift + End",
    platform: "Windows",
  },
  {
    id: "word-75",
    app: "MS Word",
    category: "Thesaurus",
    title: "Thesaurus",
    description: "Open thesaurus",
    keys: "Shift + F7",
    platform: "Windows",
  },
  {
    id: "word-76",
    app: "MS Word",
    category: "Objects",
    title: "Insert Table of Contents",
    description: "Insert table of contents",
    keys: "Alt + Ctrl + W",
    platform: "Windows",
  },
  {
    id: "word-77",
    app: "MS Word",
    category: "Objects",
    title: "Update Table of Contents",
    description: "Update table of contents",
    keys: "F9",
    platform: "Windows",
  },
  {
    id: "word-78",
    app: "MS Word",
    category: "Objects",
    title: "Insert Index",
    description: "Insert index",
    keys: "Alt + Ctrl + I",
    platform: "Windows",
  },
  {
    id: "word-79",
    app: "MS Word",
    category: "Paragraphs",
    title: "Single Space",
    description: "Set single line spacing",
    keys: "Ctrl + 1",
    platform: "Windows",
  },
  {
    id: "word-80",
    app: "MS Word",
    category: "Paragraphs",
    title: "Double Space",
    description: "Set double line spacing",
    keys: "Ctrl + 2",
    platform: "Windows",
  },
  {
    id: "word-81",
    app: "MS Word",
    category: "Paragraphs",
    title: "1.5 Line Spacing",
    description: "Set 1.5 line spacing",
    keys: "Ctrl + 5",
    platform: "Windows",
  },
  {
    id: "word-82",
    app: "MS Word",
    category: "Paragraphs",
    title: "Add Space Before",
    description: "Add space before paragraph",
    keys: "Ctrl + 0",
    platform: "Windows",
  },
  {
    id: "word-83",
    app: "MS Word",
    category: "Font Color",
    title: "Font Color",
    description: "Change font color",
    keys: "Ctrl + D then Alt + C",
    platform: "Windows",
  },
  {
    id: "word-84",
    app: "MS Word",
    category: "Highlight",
    title: "Highlight Color",
    description: "Apply highlight color",
    keys: "Alt + Ctrl + H",
    platform: "Windows",
  },
  {
    id: "word-85",
    app: "MS Word",
    category: "Line Breaks",
    title: "Line Break",
    description: "Insert line break",
    keys: "Shift + Return",
    platform: "Windows",
  },
  {
    id: "word-86",
    app: "MS Word",
    category: "Navigation",
    title: "Move by Word",
    description: "Move cursor by word",
    keys: "Ctrl + Left/Right",
    platform: "Windows",
  },
  {
    id: "word-87",
    app: "MS Word",
    category: "Navigation",
    title: "Move by Paragraph",
    description: "Move cursor by paragraph",
    keys: "Ctrl + Up/Down",
    platform: "Windows",
  },
  {
    id: "word-88",
    app: "MS Word",
    category: "Editing",
    title: "Repeat Last Action",
    description: "Repeat last performed action",
    keys: "Ctrl + Shift + Y",
    platform: "Windows",
  },
  {
    id: "word-89",
    app: "MS Word",
    category: "View",
    title: "Reading Mode",
    description: "Switch to Reading view",
    keys: "Alt + V then R",
    platform: "Windows",
  },
  {
    id: "word-90",
    app: "MS Word",
    category: "Tools",
    title: "Word Count",
    description: "Show word count",
    keys: "Ctrl + Shift + G",
    platform: "Windows",
  },
  {
    id: "word-91",
    app: "MS Word",
    category: "Tools",
    title: "Grammar Check",
    description: "Check grammar",
    keys: "Ctrl + Shift + G",
    platform: "Windows",
  },
  {
    id: "word-92",
    app: "MS Word",
    category: "Tools",
    title: "Accessibility Check",
    description: "Check accessibility",
    keys: "Alt + Ctrl + Alt",
    platform: "Windows",
  },
  {
    id: "word-93",
    app: "MS Word",
    category: "Print Preview",
    title: "Print Preview",
    description: "Preview before printing",
    keys: "Ctrl + Alt + I",
    platform: "Windows",
  },
  {
    id: "word-94",
    app: "MS Word",
    category: "Mail Merge",
    title: "Mail Merge",
    description: "Start mail merge wizard",
    keys: "Alt + M then M",
    platform: "Windows",
  },
  {
    id: "word-95",
    app: "MS Word",
    category: "Macros",
    title: "Run Macro",
    description: "Run a macro",
    keys: "Alt + F8",
    platform: "Windows",
  },
  {
    id: "word-96",
    app: "MS Word",
    category: "Macros",
    title: "Edit Macro",
    description: "Edit a macro",
    keys: "Alt + F11",
    platform: "Windows",
  },
  {
    id: "word-97",
    app: "MS Word",
    category: "Fields",
    title: "Insert Field",
    description: "Insert merge field",
    keys: "Ctrl + F9",
    platform: "Windows",
  },
  {
    id: "word-98",
    app: "MS Word",
    category: "Fields",
    title: "Update Field",
    description: "Update field values",
    keys: "F9",
    platform: "Windows",
  },
  {
    id: "word-99",
    app: "MS Word",
    category: "Fields",
    title: "Unlink Field",
    description: "Convert field to text",
    keys: "Ctrl + Shift + F9",
    platform: "Windows",
  },
  {
    id: "word-100",
    app: "MS Word",
    category: "Advanced",
    title: "Toggle Field Codes",
    description: "Show/hide field codes",
    keys: "Alt + F9",
    platform: "Windows",
  },

  // MS EXCEL - 100+ shortcuts
  {
    id: "excel-1",
    app: "MS Excel",
    category: "File Operations",
    title: "New Workbook",
    description: "Create new workbook",
    keys: "Ctrl + N",
    platform: "Windows",
  },
  {
    id: "excel-2",
    app: "MS Excel",
    category: "File Operations",
    title: "Open Workbook",
    description: "Open existing workbook",
    keys: "Ctrl + O",
    platform: "Windows",
  },
  {
    id: "excel-3",
    app: "MS Excel",
    category: "File Operations",
    title: "Save",
    description: "Save workbook",
    keys: "Ctrl + S",
    platform: "Windows",
  },
  {
    id: "excel-4",
    app: "MS Excel",
    category: "File Operations",
    title: "Close Workbook",
    description: "Close current workbook",
    keys: "Ctrl + W",
    platform: "Windows",
  },
  {
    id: "excel-5",
    app: "MS Excel",
    category: "File Operations",
    title: "Print",
    description: "Print worksheet",
    keys: "Ctrl + P",
    platform: "Windows",
  },
  {
    id: "excel-6",
    app: "MS Excel",
    category: "File Operations",
    title: "Export as PDF",
    description: "Export to PDF",
    keys: "Ctrl + Shift + X",
    platform: "Windows",
  },
  {
    id: "excel-7",
    app: "MS Excel",
    category: "Editing",
    title: "Undo",
    description: "Undo last action",
    keys: "Ctrl + Z",
    platform: "Windows",
  },
  {
    id: "excel-8",
    app: "MS Excel",
    category: "Editing",
    title: "Redo",
    description: "Redo last undo",
    keys: "Ctrl + Y",
    platform: "Windows",
  },
  {
    id: "excel-9",
    app: "MS Excel",
    category: "Editing",
    title: "Cut",
    description: "Cut selected cells",
    keys: "Ctrl + X",
    platform: "Windows",
  },
  {
    id: "excel-10",
    app: "MS Excel",
    category: "Editing",
    title: "Copy",
    description: "Copy selected cells",
    keys: "Ctrl + C",
    platform: "Windows",
  },
  {
    id: "excel-11",
    app: "MS Excel",
    category: "Editing",
    title: "Paste",
    description: "Paste clipboard",
    keys: "Ctrl + V",
    platform: "Windows",
  },
  {
    id: "excel-12",
    app: "MS Excel",
    category: "Editing",
    title: "Paste Special",
    description: "Paste special options",
    keys: "Ctrl + Alt + V",
    platform: "Windows",
  },
  {
    id: "excel-13",
    app: "MS Excel",
    category: "Editing",
    title: "Select All",
    description: "Select all cells",
    keys: "Ctrl + A",
    platform: "Windows",
  },
  {
    id: "excel-14",
    app: "MS Excel",
    category: "Editing",
    title: "Find",
    description: "Open find dialog",
    keys: "Ctrl + F",
    platform: "Windows",
  },
  {
    id: "excel-15",
    app: "MS Excel",
    category: "Editing",
    title: "Find and Replace",
    description: "Find and replace",
    keys: "Ctrl + H",
    platform: "Windows",
  },
  {
    id: "excel-16",
    app: "MS Excel",
    category: "Cells",
    title: "Insert Cell",
    description: "Insert new cell",
    keys: "Ctrl + + (plus)",
    platform: "Windows",
  },
  {
    id: "excel-17",
    app: "MS Excel",
    category: "Cells",
    title: "Delete Cell",
    description: "Delete selected cell",
    keys: "Ctrl + - (minus)",
    platform: "Windows",
  },
  {
    id: "excel-18",
    app: "MS Excel",
    category: "Cells",
    title: "Clear Contents",
    description: "Clear cell contents",
    keys: "Delete",
    platform: "Windows",
  },
  {
    id: "excel-19",
    app: "MS Excel",
    category: "Formatting",
    title: "Bold",
    description: "Make text bold",
    keys: "Ctrl + B",
    platform: "Windows",
  },
  {
    id: "excel-20",
    app: "MS Excel",
    category: "Formatting",
    title: "Italic",
    description: "Make text italic",
    keys: "Ctrl + I",
    platform: "Windows",
  },
  {
    id: "excel-21",
    app: "MS Excel",
    category: "Formatting",
    title: "Underline",
    description: "Underline text",
    keys: "Ctrl + U",
    platform: "Windows",
  },
  {
    id: "excel-22",
    app: "MS Excel",
    category: "Formatting",
    title: "Format Cells",
    description: "Open format cells dialog",
    keys: "Ctrl + 1",
    platform: "Windows",
  },
  {
    id: "excel-23",
    app: "MS Excel",
    category: "Formatting",
    title: "Currency Format",
    description: "Apply currency format",
    keys: "Ctrl + Shift + 4",
    platform: "Windows",
  },
  {
    id: "excel-24",
    app: "MS Excel",
    category: "Formatting",
    title: "Percentage Format",
    description: "Apply percentage format",
    keys: "Ctrl + Shift + 5",
    platform: "Windows",
  },
  {
    id: "excel-25",
    app: "MS Excel",
    category: "Formatting",
    title: "Date Format",
    description: "Apply date format",
    keys: "Ctrl + Shift + 3",
    platform: "Windows",
  },
  {
    id: "excel-26",
    app: "MS Excel",
    category: "Formatting",
    title: "Time Format",
    description: "Apply time format",
    keys: "Ctrl + Shift + 2",
    platform: "Windows",
  },
  {
    id: "excel-27",
    app: "MS Excel",
    category: "Formatting",
    title: "Number Format",
    description: "Apply number format",
    keys: "Ctrl + Shift + 1",
    platform: "Windows",
  },
  {
    id: "excel-28",
    app: "MS Excel",
    category: "Formatting",
    title: "Scientific Format",
    description: "Apply scientific format",
    keys: "Ctrl + Shift + 6",
    platform: "Windows",
  },
  {
    id: "excel-29",
    app: "MS Excel",
    category: "Rows & Columns",
    title: "Insert Row",
    description: "Insert row above",
    keys: "Ctrl + Shift + + (R)",
    platform: "Windows",
  },
  {
    id: "excel-30",
    app: "MS Excel",
    category: "Rows & Columns",
    title: "Delete Row",
    description: "Delete selected row",
    keys: "Ctrl + - (minus)",
    platform: "Windows",
  },
  {
    id: "excel-31",
    app: "MS Excel",
    category: "Rows & Columns",
    title: "Insert Column",
    description: "Insert column left",
    keys: "Ctrl + Shift + + (C)",
    platform: "Windows",
  },
  {
    id: "excel-32",
    app: "MS Excel",
    category: "Rows & Columns",
    title: "Delete Column",
    description: "Delete selected column",
    keys: "Ctrl + - (minus)",
    platform: "Windows",
  },
  {
    id: "excel-33",
    app: "MS Excel",
    category: "Navigation",
    title: "Go to Beginning",
    description: "Go to cell A1",
    keys: "Ctrl + Home",
    platform: "Windows",
  },
  {
    id: "excel-34",
    app: "MS Excel",
    category: "Navigation",
    title: "Go to End",
    description: "Go to last cell",
    keys: "Ctrl + End",
    platform: "Windows",
  },
  {
    id: "excel-35",
    app: "MS Excel",
    category: "Navigation",
    title: "Navigate Cell",
    description: "Open go to dialog",
    keys: "Ctrl + G or F5",
    platform: "Windows",
  },
  {
    id: "excel-36",
    app: "MS Excel",
    category: "Formulas",
    title: "Sum",
    description: "Insert SUM formula",
    keys: "Alt + =",
    platform: "Windows",
  },
  {
    id: "excel-37",
    app: "MS Excel",
    category: "Formulas",
    title: "Average",
    description: "Insert AVERAGE formula",
    keys: "Alt + Ctrl + A",
    platform: "Windows",
  },
  {
    id: "excel-38",
    app: "MS Excel",
    category: "Formulas",
    title: "Count",
    description: "Insert COUNT formula",
    keys: "Alt + Ctrl + N",
    platform: "Windows",
  },
  {
    id: "excel-39",
    app: "MS Excel",
    category: "Formulas",
    title: "Enter Formula",
    description: "Start entering formula",
    keys: "=",
    platform: "Windows",
  },
  {
    id: "excel-40",
    app: "MS Excel",
    category: "Formulas",
    title: "Edit Cell Formula",
    description: "Edit cell formula",
    keys: "F2",
    platform: "Windows",
  },
  {
    id: "excel-41",
    app: "MS Excel",
    category: "Formulas",
    title: "Expand Formula",
    description: "Show formula bar",
    keys: "Ctrl + Shift + U",
    platform: "Windows",
  },
  {
    id: "excel-42",
    app: "MS Excel",
    category: "Formulas",
    title: "Function Wizard",
    description: "Open function wizard",
    keys: "Ctrl + Shift + F3",
    platform: "Windows",
  },
  {
    id: "excel-43",
    app: "MS Excel",
    category: "Data Entry",
    title: "Auto Fill Down",
    description: "Fill down selected cells",
    keys: "Ctrl + D",
    platform: "Windows",
  },
  {
    id: "excel-44",
    app: "MS Excel",
    category: "Data Entry",
    title: "Auto Fill Right",
    description: "Fill right selected cells",
    keys: "Ctrl + R",
    platform: "Windows",
  },
  {
    id: "excel-45",
    app: "MS Excel",
    category: "Data Entry",
    title: "Auto Fill Series",
    description: "Fill series",
    keys: "Ctrl + Shift + Alt + Right",
    platform: "Windows",
  },
  {
    id: "excel-46",
    app: "MS Excel",
    category: "Data Entry",
    title: "New Line in Cell",
    description: "Add new line in cell",
    keys: "Alt + Enter",
    platform: "Windows",
  },
  {
    id: "excel-47",
    app: "MS Excel",
    category: "Sheets",
    title: "Insert Sheet",
    description: "Insert new sheet",
    keys: "Alt + Shift + F1",
    platform: "Windows",
  },
  {
    id: "excel-48",
    app: "MS Excel",
    category: "Sheets",
    title: "Delete Sheet",
    description: "Delete current sheet",
    keys: "Alt + E then D",
    platform: "Windows",
  },
  {
    id: "excel-49",
    app: "MS Excel",
    category: "Sheets",
    title: "Next Sheet",
    description: "Navigate to next sheet",
    keys: "Ctrl + Page Down",
    platform: "Windows",
  },
  {
    id: "excel-50",
    app: "MS Excel",
    category: "Sheets",
    title: "Previous Sheet",
    description: "Navigate to previous sheet",
    keys: "Ctrl + Page Up",
    platform: "Windows",
  },
  {
    id: "excel-51",
    app: "MS Excel",
    category: "Sorting",
    title: "Sort Ascending",
    description: "Sort selected data ascending",
    keys: "Alt + D then S then A",
    platform: "Windows",
  },
  {
    id: "excel-52",
    app: "MS Excel",
    category: "Sorting",
    title: "Sort Descending",
    description: "Sort selected data descending",
    keys: "Alt + D then S then D",
    platform: "Windows",
  },
  {
    id: "excel-53",
    app: "MS Excel",
    category: "Filtering",
    title: "AutoFilter",
    description: "Toggle autofilter",
    keys: "Ctrl + Shift + L",
    platform: "Windows",
  },
  {
    id: "excel-54",
    app: "MS Excel",
    category: "Filtering",
    title: "Standard Filter",
    description: "Open standard filter",
    keys: "Alt + D then F then S",
    platform: "Windows",
  },
  {
    id: "excel-55",
    app: "MS Excel",
    category: "PivotTable",
    title: "Insert PivotTable",
    description: "Insert pivot table",
    keys: "Alt + D then P then I",
    platform: "Windows",
  },
  {
    id: "excel-56",
    app: "MS Excel",
    category: "Charts",
    title: "Insert Chart",
    description: "Insert chart",
    keys: "Alt + I then C",
    platform: "Windows",
  },
  {
    id: "excel-57",
    app: "MS Excel",
    category: "Charts",
    title: "Edit Chart",
    description: "Edit selected chart",
    keys: "Enter",
    platform: "Windows",
  },
  {
    id: "excel-58",
    app: "MS Excel",
    category: "Conditional Formatting",
    title: "Conditional Formatting",
    description: "Apply conditional formatting",
    keys: "Alt + O then D",
    platform: "Windows",
  },
  {
    id: "excel-59",
    app: "MS Excel",
    category: "Validation",
    title: "Data Validation",
    description: "Set data validation",
    keys: "Alt + D then V",
    platform: "Windows",
  },
  {
    id: "excel-60",
    app: "MS Excel",
    category: "Comments",
    title: "Insert Comment",
    description: "Insert cell comment",
    keys: "Ctrl + Alt + C",
    platform: "Windows",
  },
  {
    id: "excel-61",
    app: "MS Excel",
    category: "Comments",
    title: "Delete Comment",
    description: "Delete cell comment",
    keys: "Alt + C then D",
    platform: "Windows",
  },
  {
    id: "excel-62",
    app: "MS Excel",
    category: "Comments",
    title: "Show All Comments",
    description: "Show all comments",
    keys: "Ctrl + Alt + E",
    platform: "Windows",
  },
  {
    id: "excel-63",
    app: "MS Excel",
    category: "Print",
    title: "Print Preview",
    description: "Preview print",
    keys: "Ctrl + Alt + I",
    platform: "Windows",
  },
  {
    id: "excel-64",
    app: "MS Excel",
    category: "Print",
    title: "Set Print Area",
    description: "Set print area",
    keys: "Alt + P then A then S",
    platform: "Windows",
  },
  {
    id: "excel-65",
    app: "MS Excel",
    category: "Zoom",
    title: "Zoom In",
    description: "Increase zoom",
    keys: "Ctrl + +",
    platform: "Windows",
  },
  {
    id: "excel-66",
    app: "MS Excel",
    category: "Zoom",
    title: "Zoom Out",
    description: "Decrease zoom",
    keys: "Ctrl + -",
    platform: "Windows",
  },
  {
    id: "excel-67",
    app: "MS Excel",
    category: "Zoom",
    title: "Reset Zoom",
    description: "Reset zoom to 100%",
    keys: "Ctrl + 0",
    platform: "Windows",
  },
  {
    id: "excel-68",
    app: "MS Excel",
    category: "View",
    title: "Freeze Panes",
    description: "Freeze panes",
    keys: "Alt + W then F",
    platform: "Windows",
  },
  {
    id: "excel-69",
    app: "MS Excel",
    category: "View",
    title: "Split Window",
    description: "Split window",
    keys: "Alt + W then S",
    platform: "Windows",
  },
  {
    id: "excel-70",
    app: "MS Excel",
    category: "Selection",
    title: "Select Row",
    description: "Select entire row",
    keys: "Shift + Spacebar",
    platform: "Windows",
  },
  {
    id: "excel-71",
    app: "MS Excel",
    category: "Selection",
    title: "Select Column",
    description: "Select entire column",
    keys: "Ctrl + Spacebar",
    platform: "Windows",
  },
  {
    id: "excel-72",
    app: "MS Excel",
    category: "Selection",
    title: "Select Region",
    description: "Select data region",
    keys: "Ctrl + A",
    platform: "Windows",
  },
  {
    id: "excel-73",
    app: "MS Excel",
    category: "Selection",
    title: "Select Adjacent",
    description: "Select adjacent cells",
    keys: "Shift + Arrow",
    platform: "Windows",
  },
  {
    id: "excel-74",
    app: "MS Excel",
    category: "Macros",
    title: "Record Macro",
    description: "Record macro",
    keys: "Alt + T then M then R",
    platform: "Windows",
  },
  {
    id: "excel-75",
    app: "MS Excel",
    category: "Macros",
    title: "Run Macro",
    description: "Run macro",
    keys: "Alt + F8",
    platform: "Windows",
  },
  {
    id: "excel-76",
    app: "MS Excel",
    category: "Links",
    title: "Edit Links",
    description: "Edit external links",
    keys: "Ctrl + Shift + Alt + L",
    platform: "Windows",
  },
  {
    id: "excel-77",
    app: "MS Excel",
    category: "Hyperlink",
    title: "Insert Hyperlink",
    description: "Insert hyperlink",
    keys: "Ctrl + K",
    platform: "Windows",
  },
  {
    id: "excel-78",
    app: "MS Excel",
    category: "Hyperlink",
    title: "Remove Hyperlink",
    description: "Remove hyperlink",
    keys: "Ctrl + Shift + F9",
    platform: "Windows",
  },
  {
    id: "excel-79",
    app: "MS Excel",
    category: "Protection",
    title: "Protect Sheet",
    description: "Protect current sheet",
    keys: "Alt + T then P then S",
    platform: "Windows",
  },
  {
    id: "excel-80",
    app: "MS Excel",
    category: "Protection",
    title: "Protect Workbook",
    description: "Protect workbook",
    keys: "Alt + T then P then W",
    platform: "Windows",
  },
  {
    id: "excel-81",
    app: "MS Excel",
    category: "Advanced",
    title: "Show Formulas",
    description: "Toggle formula display",
    keys: "Ctrl + `",
    platform: "Windows",
  },
  {
    id: "excel-82",
    app: "MS Excel",
    category: "Advanced",
    title: "Trace Precedents",
    description: "Show formula precedents",
    keys: "Ctrl + [",
    platform: "Windows",
  },
  {
    id: "excel-83",
    app: "MS Excel",
    category: "Advanced",
    title: "Trace Dependents",
    description: "Show formula dependents",
    keys: "Ctrl + ]",
    platform: "Windows",
  },
  {
    id: "excel-84",
    app: "MS Excel",
    category: "Advanced",
    title: "Error Checking",
    description: "Toggle error checking",
    keys: "Ctrl + Alt + E",
    platform: "Windows",
  },
  {
    id: "excel-85",
    app: "MS Excel",
    category: "Goals",
    title: "Goal Seek",
    description: "Open goal seek",
    keys: "Alt + T then G then S",
    platform: "Windows",
  },
  {
    id: "excel-86",
    app: "MS Excel",
    category: "Goals",
    title: "Scenario Manager",
    description: "Open scenario manager",
    keys: "Alt + T then S",
    platform: "Windows",
  },
  {
    id: "excel-87",
    app: "MS Excel",
    category: "Text to Columns",
    title: "Text to Columns",
    description: "Text to columns wizard",
    keys: "Alt + D then E",
    platform: "Windows",
  },
  {
    id: "excel-88",
    app: "MS Excel",
    category: "Subtotals",
    title: "Subtotals",
    description: "Insert subtotals",
    keys: "Alt + D then S then T",
    platform: "Windows",
  },
  {
    id: "excel-89",
    app: "MS Excel",
    category: "Outline",
    title: "Group Outline",
    description: "Group rows/columns",
    keys: "Ctrl + Alt + G",
    platform: "Windows",
  },
  {
    id: "excel-90",
    app: "MS Excel",
    category: "Outline",
    title: "Ungroup Outline",
    description: "Ungroup rows/columns",
    keys: "Ctrl + Alt + U",
    platform: "Windows",
  },
  {
    id: "excel-91",
    app: "MS Excel",
    category: "Sparklines",
    title: "Insert Sparkline",
    description: "Insert mini chart",
    keys: "Alt + I then K",
    platform: "Windows",
  },
  {
    id: "excel-92",
    app: "MS Excel",
    category: "Names",
    title: "Define Name",
    description: "Define named range",
    keys: "Ctrl + F3",
    platform: "Windows",
  },
  {
    id: "excel-93",
    app: "MS Excel",
    category: "Names",
    title: "Paste Name",
    description: "Paste named range",
    keys: "Ctrl + Shift + F3",
    platform: "Windows",
  },
  {
    id: "excel-94",
    app: "MS Excel",
    category: "Navigation",
    title: "Next Cell",
    description: "Move to next cell",
    keys: "Tab",
    platform: "Windows",
  },
  {
    id: "excel-95",
    app: "MS Excel",
    category: "Navigation",
    title: "Previous Cell",
    description: "Move to previous cell",
    keys: "Shift + Tab",
    platform: "Windows",
  },
  {
    id: "excel-96",
    app: "MS Excel",
    category: "Navigation",
    title: "Page Up",
    description: "Scroll up",
    keys: "Page Up",
    platform: "Windows",
  },
  {
    id: "excel-97",
    app: "MS Excel",
    category: "Navigation",
    title: "Page Down",
    description: "Scroll down",
    keys: "Page Down",
    platform: "Windows",
  },
  {
    id: "excel-98",
    app: "MS Excel",
    category: "Navigation",
    title: "Move by Screen",
    description: "Move by screen",
    keys: "Alt + Page Down",
    platform: "Windows",
  },
  {
    id: "excel-99",
    app: "MS Excel",
    category: "Navigation",
    title: "Move Back by Screen",
    description: "Move back by screen",
    keys: "Alt + Page Up",
    platform: "Windows",
  },
  {
    id: "excel-100",
    app: "MS Excel",
    category: "Help",
    title: "Help",
    description: "Open help",
    keys: "F1",
    platform: "Windows",
  },

  // VS CODE - 100+ shortcuts
  {
    id: "vscode-1",
    app: "VS Code",
    category: "File Management",
    title: "New File",
    description: "Create new file",
    keys: "Ctrl + N",
    platform: "Windows",
  },
  {
    id: "vscode-2",
    app: "VS Code",
    category: "File Management",
    title: "Open File",
    description: "Open file dialog",
    keys: "Ctrl + O",
    platform: "Windows",
  },
  {
    id: "vscode-3",
    app: "VS Code",
    category: "File Management",
    title: "Open Folder",
    description: "Open folder",
    keys: "Ctrl + K Ctrl + O",
    platform: "Windows",
  },
  {
    id: "vscode-4",
    app: "VS Code",
    category: "File Management",
    title: "Save",
    description: "Save file",
    keys: "Ctrl + S",
    platform: "Windows",
  },
  {
    id: "vscode-5",
    app: "VS Code",
    category: "File Management",
    title: "Save All",
    description: "Save all files",
    keys: "Ctrl + Alt + S",
    platform: "Windows",
  },
  {
    id: "vscode-6",
    app: "VS Code",
    category: "File Management",
    title: "Close",
    description: "Close current file",
    keys: "Ctrl + W",
    platform: "Windows",
  },
  {
    id: "vscode-7",
    app: "VS Code",
    category: "File Management",
    title: "Close All",
    description: "Close all files",
    keys: "Ctrl + K W",
    platform: "Windows",
  },
  {
    id: "vscode-8",
    app: "VS Code",
    category: "Navigation",
    title: "Go to File",
    description: "Quick file open",
    keys: "Ctrl + P",
    platform: "Windows",
  },
  {
    id: "vscode-9",
    app: "VS Code",
    category: "Navigation",
    title: "Go to Line",
    description: "Jump to line",
    keys: "Ctrl + G",
    platform: "Windows",
  },
  {
    id: "vscode-10",
    app: "VS Code",
    category: "Navigation",
    title: "Go to Symbol",
    description: "Open symbol explorer",
    keys: "Ctrl + Shift + O",
    platform: "Windows",
  },
  {
    id: "vscode-11",
    app: "VS Code",
    category: "Navigation",
    title: "Go to Definition",
    description: "Jump to definition",
    keys: "F12",
    platform: "Windows",
  },
  {
    id: "vscode-12",
    app: "VS Code",
    category: "Navigation",
    title: "Peek Definition",
    description: "Preview definition",
    keys: "Alt + F12",
    platform: "Windows",
  },
  {
    id: "vscode-13",
    app: "VS Code",
    category: "Navigation",
    title: "Go to References",
    description: "Find all references",
    keys: "Shift + F12",
    platform: "Windows",
  },
  {
    id: "vscode-14",
    app: "VS Code",
    category: "Navigation",
    title: "Back",
    description: "Navigate back",
    keys: "Alt + Left",
    platform: "Windows",
  },
  {
    id: "vscode-15",
    app: "VS Code",
    category: "Navigation",
    title: "Forward",
    description: "Navigate forward",
    keys: "Alt + Right",
    platform: "Windows",
  },
  {
    id: "vscode-16",
    app: "VS Code",
    category: "Editing",
    title: "Undo",
    description: "Undo last change",
    keys: "Ctrl + Z",
    platform: "Windows",
  },
  {
    id: "vscode-17",
    app: "VS Code",
    category: "Editing",
    title: "Redo",
    description: "Redo last undo",
    keys: "Ctrl + Shift + Z",
    platform: "Windows",
  },
  {
    id: "vscode-18",
    app: "VS Code",
    category: "Editing",
    title: "Cut",
    description: "Cut selected text",
    keys: "Ctrl + X",
    platform: "Windows",
  },
  {
    id: "vscode-19",
    app: "VS Code",
    category: "Editing",
    title: "Copy",
    description: "Copy selected text",
    keys: "Ctrl + C",
    platform: "Windows",
  },
  {
    id: "vscode-20",
    app: "VS Code",
    category: "Editing",
    title: "Paste",
    description: "Paste from clipboard",
    keys: "Ctrl + V",
    platform: "Windows",
  },
  {
    id: "vscode-21",
    app: "VS Code",
    category: "Editing",
    title: "Select All",
    description: "Select all text",
    keys: "Ctrl + A",
    platform: "Windows",
  },
  {
    id: "vscode-22",
    app: "VS Code",
    category: "Editing",
    title: "Find",
    description: "Open find dialog",
    keys: "Ctrl + F",
    platform: "Windows",
  },
  {
    id: "vscode-23",
    app: "VS Code",
    category: "Editing",
    title: "Find and Replace",
    description: "Open find and replace",
    keys: "Ctrl + H",
    platform: "Windows",
  },
  {
    id: "vscode-24",
    app: "VS Code",
    category: "Editing",
    title: "Find Next",
    description: "Find next match",
    keys: "Enter",
    platform: "Windows",
  },
  {
    id: "vscode-25",
    app: "VS Code",
    category: "Editing",
    title: "Find Previous",
    description: "Find previous match",
    keys: "Shift + Enter",
    platform: "Windows",
  },
  {
    id: "vscode-26",
    app: "VS Code",
    category: "Selection",
    title: "Select Word",
    description: "Double click or Ctrl+D",
    keys: "Ctrl + D",
    platform: "Windows",
  },
  {
    id: "vscode-27",
    app: "VS Code",
    category: "Selection",
    title: "Expand Selection",
    description: "Expand selection to bracket",
    keys: "Ctrl + Shift + \\",
    platform: "Windows",
  },
  {
    id: "vscode-28",
    app: "VS Code",
    category: "Selection",
    title: "Select Line",
    description: "Select entire line",
    keys: "Ctrl + L",
    platform: "Windows",
  },
  {
    id: "vscode-29",
    app: "VS Code",
    category: "Selection",
    title: "Select to End",
    description: "Select to end of line",
    keys: "Shift + End",
    platform: "Windows",
  },
  {
    id: "vscode-30",
    app: "VS Code",
    category: "Selection",
    title: "Select to Beginning",
    description: "Select to start of line",
    keys: "Shift + Home",
    platform: "Windows",
  },
  {
    id: "vscode-31",
    app: "VS Code",
    category: "Formatting",
    title: "Format Document",
    description: "Format entire document",
    keys: "Shift + Alt + F",
    platform: "Windows",
  },
  {
    id: "vscode-32",
    app: "VS Code",
    category: "Formatting",
    title: "Format Selection",
    description: "Format selected code",
    keys: "Ctrl + K Ctrl + F",
    platform: "Windows",
  },
  {
    id: "vscode-33",
    app: "VS Code",
    category: "Formatting",
    title: "Indent",
    description: "Increase indent",
    keys: "Tab",
    platform: "Windows",
  },
  {
    id: "vscode-34",
    app: "VS Code",
    category: "Formatting",
    title: "Outdent",
    description: "Decrease indent",
    keys: "Shift + Tab",
    platform: "Windows",
  },
  {
    id: "vscode-35",
    app: "VS Code",
    category: "Formatting",
    title: "Toggle Line Comment",
    description: "Comment/uncomment line",
    keys: "Ctrl + /",
    platform: "Windows",
  },
  {
    id: "vscode-36",
    app: "VS Code",
    category: "Formatting",
    title: "Toggle Block Comment",
    description: "Comment/uncomment block",
    keys: "Shift + Alt + A",
    platform: "Windows",
  },
  {
    id: "vscode-37",
    app: "VS Code",
    category: "Lines",
    title: "Move Line Up",
    description: "Move line up",
    keys: "Alt + Up",
    platform: "Windows",
  },
  {
    id: "vscode-38",
    app: "VS Code",
    category: "Lines",
    title: "Move Line Down",
    description: "Move line down",
    keys: "Alt + Down",
    platform: "Windows",
  },
  {
    id: "vscode-39",
    app: "VS Code",
    category: "Lines",
    title: "Copy Line Up",
    description: "Duplicate line up",
    keys: "Shift + Alt + Up",
    platform: "Windows",
  },
  {
    id: "vscode-40",
    app: "VS Code",
    category: "Lines",
    title: "Copy Line Down",
    description: "Duplicate line down",
    keys: "Shift + Alt + Down",
    platform: "Windows",
  },
  {
    id: "vscode-41",
    app: "VS Code",
    category: "Lines",
    title: "Delete Line",
    description: "Delete entire line",
    keys: "Ctrl + Shift + K",
    platform: "Windows",
  },
  {
    id: "vscode-42",
    app: "VS Code",
    category: "Lines",
    title: "Insert Line Below",
    description: "Insert line below",
    keys: "Ctrl + Enter",
    platform: "Windows",
  },
  {
    id: "vscode-43",
    app: "VS Code",
    category: "Lines",
    title: "Insert Line Above",
    description: "Insert line above",
    keys: "Ctrl + Shift + Enter",
    platform: "Windows",
  },
  {
    id: "vscode-44",
    app: "VS Code",
    category: "Cursor",
    title: "Go to Start",
    description: "Move to file start",
    keys: "Ctrl + Home",
    platform: "Windows",
  },
  {
    id: "vscode-45",
    app: "VS Code",
    category: "Cursor",
    title: "Go to End",
    description: "Move to file end",
    keys: "Ctrl + End",
    platform: "Windows",
  },
  {
    id: "vscode-46",
    app: "VS Code",
    category: "Cursor",
    title: "Page Up",
    description: "Page up",
    keys: "Page Up",
    platform: "Windows",
  },
  {
    id: "vscode-47",
    app: "VS Code",
    category: "Cursor",
    title: "Page Down",
    description: "Page down",
    keys: "Page Down",
    platform: "Windows",
  },
  {
    id: "vscode-48",
    app: "VS Code",
    category: "Cursor",
    title: "Start of Line",
    description: "Move to line start",
    keys: "Home",
    platform: "Windows",
  },
  {
    id: "vscode-49",
    app: "VS Code",
    category: "Cursor",
    title: "End of Line",
    description: "Move to line end",
    keys: "End",
    platform: "Windows",
  },
  {
    id: "vscode-50",
    app: "VS Code",
    category: "IntelliSense",
    title: "Trigger IntelliSense",
    description: "Open autocomplete",
    keys: "Ctrl + Space",
    platform: "Windows",
  },
  {
    id: "vscode-51",
    app: "VS Code",
    category: "IntelliSense",
    title: "Trigger Parameter Hints",
    description: "Show parameter hints",
    keys: "Ctrl + Shift + Space",
    platform: "Windows",
  },
  {
    id: "vscode-52",
    app: "VS Code",
    category: "IntelliSense",
    title: "Format Parameters",
    description: "Format parameters",
    keys: "Ctrl + Alt + Space",
    platform: "Windows",
  },
  {
    id: "vscode-53",
    app: "VS Code",
    category: "Refactoring",
    title: "Refactor",
    description: "Open refactor menu",
    keys: "Ctrl + Shift + R",
    platform: "Windows",
  },
  {
    id: "vscode-54",
    app: "VS Code",
    category: "Refactoring",
    title: "Rename Symbol",
    description: "Rename symbol",
    keys: "F2",
    platform: "Windows",
  },
  {
    id: "vscode-55",
    app: "VS Code",
    category: "Refactoring",
    title: "Quick Fix",
    description: "Quick fix menu",
    keys: "Ctrl + .",
    platform: "Windows",
  },
  {
    id: "vscode-56",
    app: "VS Code",
    category: "Terminal",
    title: "Toggle Terminal",
    description: "Show/hide terminal",
    keys: "Ctrl + `",
    platform: "Windows",
  },
  {
    id: "vscode-57",
    app: "VS Code",
    category: "Terminal",
    title: "New Terminal",
    description: "Create new terminal",
    keys: "Ctrl + Shift + `",
    platform: "Windows",
  },
  {
    id: "vscode-58",
    app: "VS Code",
    category: "Terminal",
    title: "Kill Terminal",
    description: "Close terminal",
    keys: "Ctrl + Shift + X",
    platform: "Windows",
  },
  {
    id: "vscode-59",
    app: "VS Code",
    category: "Debug",
    title: "Toggle Breakpoint",
    description: "Set/unset breakpoint",
    keys: "F9",
    platform: "Windows",
  },
  {
    id: "vscode-60",
    app: "VS Code",
    category: "Debug",
    title: "Start Debugging",
    description: "Start debug session",
    keys: "F5",
    platform: "Windows",
  },
  {
    id: "vscode-61",
    app: "VS Code",
    category: "Debug",
    title: "Continue",
    description: "Continue execution",
    keys: "F5",
    platform: "Windows",
  },
  {
    id: "vscode-62",
    app: "VS Code",
    category: "Debug",
    title: "Step Over",
    description: "Step over statement",
    keys: "F10",
    platform: "Windows",
  },
  {
    id: "vscode-63",
    app: "VS Code",
    category: "Debug",
    title: "Step Into",
    description: "Step into function",
    keys: "F11",
    platform: "Windows",
  },
  {
    id: "vscode-64",
    app: "VS Code",
    category: "Debug",
    title: "Step Out",
    description: "Step out of function",
    keys: "Shift + F11",
    platform: "Windows",
  },
  {
    id: "vscode-65",
    app: "VS Code",
    category: "Debug",
    title: "Stop Debugging",
    description: "Stop debug session",
    keys: "Shift + F5",
    platform: "Windows",
  },
  {
    id: "vscode-66",
    app: "VS Code",
    category: "Source Control",
    title: "Open Source Control",
    description: "Show source control",
    keys: "Ctrl + Shift + G",
    platform: "Windows",
  },
  {
    id: "vscode-67",
    app: "VS Code",
    category: "Extensions",
    title: "Open Extensions",
    description: "Show extensions",
    keys: "Ctrl + Shift + X",
    platform: "Windows",
  },
  {
    id: "vscode-68",
    app: "VS Code",
    category: "Command Palette",
    title: "Command Palette",
    description: "Open command palette",
    keys: "Ctrl + Shift + P",
    platform: "Windows",
  },
  {
    id: "vscode-69",
    app: "VS Code",
    category: "Settings",
    title: "Open Settings",
    description: "Open settings",
    keys: "Ctrl + ,",
    platform: "Windows",
  },
  {
    id: "vscode-70",
    app: "VS Code",
    category: "Keybindings",
    title: "Open Keybindings",
    description: "Show keybindings",
    keys: "Ctrl + K Ctrl + S",
    platform: "Windows",
  },
  {
    id: "vscode-71",
    app: "VS Code",
    category: "View",
    title: "Toggle Sidebar",
    description: "Show/hide sidebar",
    keys: "Ctrl + B",
    platform: "Windows",
  },
  {
    id: "vscode-72",
    app: "VS Code",
    category: "View",
    title: "Explorer",
    description: "Show file explorer",
    keys: "Ctrl + Shift + E",
    platform: "Windows",
  },
  {
    id: "vscode-73",
    app: "VS Code",
    category: "View",
    title: "Search",
    description: "Show search panel",
    keys: "Ctrl + Shift + F",
    platform: "Windows",
  },
  {
    id: "vscode-74",
    app: "VS Code",
    category: "View",
    title: "Run and Debug",
    description: "Show run/debug panel",
    keys: "Ctrl + Shift + D",
    platform: "Windows",
  },
  {
    id: "vscode-75",
    app: "VS Code",
    category: "View",
    title: "Output",
    description: "Show output panel",
    keys: "Ctrl + K Ctrl + H",
    platform: "Windows",
  },
  {
    id: "vscode-76",
    app: "VS Code",
    category: "View",
    title: "Problems",
    description: "Show problems",
    keys: "Ctrl + Shift + M",
    platform: "Windows",
  },
  {
    id: "vscode-77",
    app: "VS Code",
    category: "View",
    title: "Debug Console",
    description: "Show debug console",
    keys: "Ctrl + Shift + Y",
    platform: "Windows",
  },
  {
    id: "vscode-78",
    app: "VS Code",
    category: "Tabs",
    title: "New Tab",
    description: "Create new editor tab",
    keys: "Ctrl + Tab",
    platform: "Windows",
  },
  {
    id: "vscode-79",
    app: "VS Code",
    category: "Tabs",
    title: "Switch Tab",
    description: "Switch to next tab",
    keys: "Ctrl + Tab",
    platform: "Windows",
  },
  {
    id: "vscode-80",
    app: "VS Code",
    category: "Tabs",
    title: "Close Tab",
    description: "Close current tab",
    keys: "Ctrl + W",
    platform: "Windows",
  },
  {
    id: "vscode-81",
    app: "VS Code",
    category: "Tabs",
    title: "Close All Tabs",
    description: "Close all tabs",
    keys: "Ctrl + K W",
    platform: "Windows",
  },
  {
    id: "vscode-82",
    app: "VS Code",
    category: "Tabs",
    title: "Close Other Tabs",
    description: "Close other tabs",
    keys: "Ctrl + K Ctrl + W",
    platform: "Windows",
  },
  {
    id: "vscode-83",
    app: "VS Code",
    category: "Split Editor",
    title: "Split Editor",
    description: "Split editor group",
    keys: "Ctrl + \\",
    platform: "Windows",
  },
  {
    id: "vscode-84",
    app: "VS Code",
    category: "Split Editor",
    title: "Focus Next Editor",
    description: "Focus next editor",
    keys: "Ctrl + K Ctrl + Right",
    platform: "Windows",
  },
  {
    id: "vscode-85",
    app: "VS Code",
    category: "Split Editor",
    title: "Focus Previous Editor",
    description: "Focus previous editor",
    keys: "Ctrl + K Ctrl + Left",
    platform: "Windows",
  },
  {
    id: "vscode-86",
    app: "VS Code",
    category: "Multi-cursor",
    title: "Add Cursor",
    description: "Add another cursor",
    keys: "Ctrl + Alt + Up/Down",
    platform: "Windows",
  },
  {
    id: "vscode-87",
    app: "VS Code",
    category: "Multi-cursor",
    title: "Add Cursor at End",
    description: "Add cursor to all occurrences",
    keys: "Ctrl + Shift + L",
    platform: "Windows",
  },
  {
    id: "vscode-88",
    app: "VS Code",
    category: "Folding",
    title: "Fold",
    description: "Fold region",
    keys: "Ctrl + Shift + [",
    platform: "Windows",
  },
  {
    id: "vscode-89",
    app: "VS Code",
    category: "Folding",
    title: "Unfold",
    description: "Unfold region",
    keys: "Ctrl + Shift + ]",
    platform: "Windows",
  },
  {
    id: "vscode-90",
    app: "VS Code",
    category: "Folding",
    title: "Fold All",
    description: "Fold all regions",
    keys: "Ctrl + K Ctrl + 0",
    platform: "Windows",
  },
  {
    id: "vscode-91",
    app: "VS Code",
    category: "Folding",
    title: "Unfold All",
    description: "Unfold all regions",
    keys: "Ctrl + K Ctrl + J",
    platform: "Windows",
  },
  {
    id: "vscode-92",
    app: "VS Code",
    category: "Breadcrumb",
    title: "Focus Breadcrumb",
    description: "Navigate breadcrumb",
    keys: "Ctrl + Shift + ;",
    platform: "Windows",
  },
  {
    id: "vscode-93",
    app: "VS Code",
    category: "Toggle Preview",
    title: "Preview Mode",
    description: "Toggle preview mode",
    keys: "Ctrl + K V",
    platform: "Windows",
  },
  {
    id: "vscode-94",
    app: "VS Code",
    category: "Zen Mode",
    title: "Zen Mode",
    description: "Toggle zen mode",
    keys: "Ctrl + K Z",
    platform: "Windows",
  },
  {
    id: "vscode-95",
    app: "VS Code",
    category: "Zen Mode",
    title: "Escape Zen Mode",
    description: "Exit zen mode",
    keys: "Escape Escape",
    platform: "Windows",
  },
  {
    id: "vscode-96",
    app: "VS Code",
    category: "Full Screen",
    title: "Full Screen",
    description: "Toggle full screen",
    keys: "F11",
    platform: "Windows",
  },
  {
    id: "vscode-97",
    app: "VS Code",
    category: "Zoom",
    title: "Zoom In",
    description: "Increase zoom",
    keys: "Ctrl + +",
    platform: "Windows",
  },
  {
    id: "vscode-98",
    app: "VS Code",
    category: "Zoom",
    title: "Zoom Out",
    description: "Decrease zoom",
    keys: "Ctrl + -",
    platform: "Windows",
  },
  {
    id: "vscode-99",
    app: "VS Code",
    category: "Zoom",
    title: "Reset Zoom",
    description: "Reset zoom",
    keys: "Ctrl + 0",
    platform: "Windows",
  },
  {
    id: "vscode-100",
    app: "VS Code",
    category: "Help",
    title: "Help",
    description: "Open help",
    keys: "F1",
    platform: "Windows",
  },

  // GIT - 100+ shortcuts (terminal commands)
  {
    id: "git-1",
    app: "Git",
    category: "Basic Setup",
    title: "Configure Username",
    description: "Set Git username",
    keys: "git config --global user.name",
    platform: "Terminal",
  },
  {
    id: "git-2",
    app: "Git",
    category: "Basic Setup",
    title: "Configure Email",
    description: "Set Git email",
    keys: "git config --global user.email",
    platform: "Terminal",
  },
  {
    id: "git-3",
    app: "Git",
    category: "Repository",
    title: "Initialize Repository",
    description: "Create new Git repo",
    keys: "git init",
    platform: "Terminal",
  },
  {
    id: "git-4",
    app: "Git",
    category: "Repository",
    title: "Clone Repository",
    description: "Clone remote repo",
    keys: "git clone <URL>",
    platform: "Terminal",
  },
  {
    id: "git-5",
    app: "Git",
    category: "Repository",
    title: "Clone with Depth",
    description: "Clone with limited history",
    keys: "git clone --depth 1 <URL>",
    platform: "Terminal",
  },
  {
    id: "git-6",
    app: "Git",
    category: "Status",
    title: "Check Status",
    description: "Show repository status",
    keys: "git status",
    platform: "Terminal",
  },
  {
    id: "git-7",
    app: "Git",
    category: "Status",
    title: "Status Short",
    description: "Short status format",
    keys: "git status -s",
    platform: "Terminal",
  },
  {
    id: "git-8",
    app: "Git",
    category: "Staging",
    title: "Add All Changes",
    description: "Stage all changes",
    keys: "git add .",
    platform: "Terminal",
  },
  {
    id: "git-9",
    app: "Git",
    category: "Staging",
    title: "Add Specific File",
    description: "Stage specific file",
    keys: "git add <file>",
    platform: "Terminal",
  },
  {
    id: "git-10",
    app: "Git",
    category: "Staging",
    title: "Add Pattern",
    description: "Stage files matching pattern",
    keys: "git add *.js",
    platform: "Terminal",
  },
  {
    id: "git-11",
    app: "Git",
    category: "Staging",
    title: "Unstage File",
    description: "Remove file from staging",
    keys: "git restore --staged <file>",
    platform: "Terminal",
  },
  {
    id: "git-12",
    app: "Git",
    category: "Staging",
    title: "Unstage All",
    description: "Unstage all files",
    keys: "git reset",
    platform: "Terminal",
  },
  {
    id: "git-13",
    app: "Git",
    category: "Commits",
    title: "Commit",
    description: "Commit staged changes",
    keys: 'git commit -m "message"',
    platform: "Terminal",
  },
  {
    id: "git-14",
    app: "Git",
    category: "Commits",
    title: "Commit All",
    description: "Stage and commit all",
    keys: 'git commit -am "message"',
    platform: "Terminal",
  },
  {
    id: "git-15",
    app: "Git",
    category: "Commits",
    title: "Amend Commit",
    description: "Modify last commit",
    keys: "git commit --amend",
    platform: "Terminal",
  },
  {
    id: "git-16",
    app: "Git",
    category: "Commits",
    title: "No-edit Amend",
    description: "Amend without edit",
    keys: "git commit --amend --no-edit",
    platform: "Terminal",
  },
  {
    id: "git-17",
    app: "Git",
    category: "Commits",
    title: "Revert Commit",
    description: "Create new commit reverting changes",
    keys: "git revert <commit>",
    platform: "Terminal",
  },
  {
    id: "git-18",
    app: "Git",
    category: "Logs",
    title: "View Log",
    description: "Show commit history",
    keys: "git log",
    platform: "Terminal",
  },
  {
    id: "git-19",
    app: "Git",
    category: "Logs",
    title: "One Line Log",
    description: "Log in oneline format",
    keys: "git log --oneline",
    platform: "Terminal",
  },
  {
    id: "git-20",
    app: "Git",
    category: "Logs",
    title: "Log with Graph",
    description: "Show commit tree",
    keys: "git log --graph --oneline --all",
    platform: "Terminal",
  },
  {
    id: "git-21",
    app: "Git",
    category: "Logs",
    title: "Log by Author",
    description: "Filter log by author",
    keys: "git log --author=<name>",
    platform: "Terminal",
  },
  {
    id: "git-22",
    app: "Git",
    category: "Logs",
    title: "Log Since Date",
    description: "Commits since date",
    keys: 'git log --since="2 weeks ago"',
    platform: "Terminal",
  },
  {
    id: "git-23",
    app: "Git",
    category: "Logs",
    title: "Show Commit",
    description: "Show commit details",
    keys: "git show <commit>",
    platform: "Terminal",
  },
  {
    id: "git-24",
    app: "Git",
    category: "Logs",
    title: "Diff Commits",
    description: "Show difference between commits",
    keys: "git diff <commit1> <commit2>",
    platform: "Terminal",
  },
  {
    id: "git-25",
    app: "Git",
    category: "Branches",
    title: "List Branches",
    description: "Show local branches",
    keys: "git branch",
    platform: "Terminal",
  },
  {
    id: "git-26",
    app: "Git",
    category: "Branches",
    title: "List Remote Branches",
    description: "Show remote branches",
    keys: "git branch -r",
    platform: "Terminal",
  },
  {
    id: "git-27",
    app: "Git",
    category: "Branches",
    title: "List All Branches",
    description: "Show all branches",
    keys: "git branch -a",
    platform: "Terminal",
  },
  {
    id: "git-28",
    app: "Git",
    category: "Branches",
    title: "Create Branch",
    description: "Create new branch",
    keys: "git branch <branch-name>",
    platform: "Terminal",
  },
  {
    id: "git-29",
    app: "Git",
    category: "Branches",
    title: "Create and Switch",
    description: "Create and checkout branch",
    keys: "git checkout -b <branch-name>",
    platform: "Terminal",
  },
  {
    id: "git-30",
    app: "Git",
    category: "Branches",
    title: "Switch Branch",
    description: "Checkout existing branch",
    keys: "git checkout <branch-name>",
    platform: "Terminal",
  },
  {
    id: "git-31",
    app: "Git",
    category: "Branches",
    title: "Rename Branch",
    description: "Rename current branch",
    keys: "git branch -m <new-name>",
    platform: "Terminal",
  },
  {
    id: "git-32",
    app: "Git",
    category: "Branches",
    title: "Delete Branch",
    description: "Delete branch",
    keys: "git branch -d <branch-name>",
    platform: "Terminal",
  },
  {
    id: "git-33",
    app: "Git",
    category: "Branches",
    title: "Force Delete Branch",
    description: "Force delete branch",
    keys: "git branch -D <branch-name>",
    platform: "Terminal",
  },
  {
    id: "git-34",
    app: "Git",
    category: "Merging",
    title: "Merge Branch",
    description: "Merge branch into current",
    keys: "git merge <branch-name>",
    platform: "Terminal",
  },
  {
    id: "git-35",
    app: "Git",
    category: "Merging",
    title: "Rebase Branch",
    description: "Rebase current branch",
    keys: "git rebase <branch-name>",
    platform: "Terminal",
  },
  {
    id: "git-36",
    app: "Git",
    category: "Merging",
    title: "Merge Abort",
    description: "Abort merge",
    keys: "git merge --abort",
    platform: "Terminal",
  },
  {
    id: "git-37",
    app: "Git",
    category: "Remotes",
    title: "List Remotes",
    description: "Show remote repositories",
    keys: "git remote",
    platform: "Terminal",
  },
  {
    id: "git-38",
    app: "Git",
    category: "Remotes",
    title: "Remote Verbose",
    description: "Show remote URLs",
    keys: "git remote -v",
    platform: "Terminal",
  },
  {
    id: "git-39",
    app: "Git",
    category: "Remotes",
    title: "Add Remote",
    description: "Add remote repository",
    keys: "git remote add <name> <URL>",
    platform: "Terminal",
  },
  {
    id: "git-40",
    app: "Git",
    category: "Remotes",
    title: "Remove Remote",
    description: "Remove remote",
    keys: "git remote remove <name>",
    platform: "Terminal",
  },
  {
    id: "git-41",
    app: "Git",
    category: "Remotes",
    title: "Show Remote",
    description: "Show remote details",
    keys: "git remote show <name>",
    platform: "Terminal",
  },
  {
    id: "git-42",
    app: "Git",
    category: "Push",
    title: "Push",
    description: "Push to remote",
    keys: "git push",
    platform: "Terminal",
  },
  {
    id: "git-43",
    app: "Git",
    category: "Push",
    title: "Push Branch",
    description: "Push specific branch",
    keys: "git push origin <branch>",
    platform: "Terminal",
  },
  {
    id: "git-44",
    app: "Git",
    category: "Push",
    title: "Push All",
    description: "Push all branches",
    keys: "git push --all",
    platform: "Terminal",
  },
  {
    id: "git-45",
    app: "Git",
    category: "Push",
    title: "Push Tags",
    description: "Push tags to remote",
    keys: "git push --tags",
    platform: "Terminal",
  },
  {
    id: "git-46",
    app: "Git",
    category: "Push",
    title: "Force Push",
    description: "Force push changes",
    keys: "git push --force",
    platform: "Terminal",
  },
  {
    id: "git-47",
    app: "Git",
    category: "Pull",
    title: "Pull",
    description: "Fetch and merge remote",
    keys: "git pull",
    platform: "Terminal",
  },
  {
    id: "git-48",
    app: "Git",
    category: "Pull",
    title: "Pull Rebase",
    description: "Pull with rebase",
    keys: "git pull --rebase",
    platform: "Terminal",
  },
  {
    id: "git-49",
    app: "Git",
    category: "Fetch",
    title: "Fetch",
    description: "Fetch from remote",
    keys: "git fetch",
    platform: "Terminal",
  },
  {
    id: "git-50",
    app: "Git",
    category: "Fetch",
    title: "Fetch All",
    description: "Fetch from all remotes",
    keys: "git fetch --all",
    platform: "Terminal",
  },
  {
    id: "git-51",
    app: "Git",
    category: "Tags",
    title: "List Tags",
    description: "Show all tags",
    keys: "git tag",
    platform: "Terminal",
  },
  {
    id: "git-52",
    app: "Git",
    category: "Tags",
    title: "Create Tag",
    description: "Create new tag",
    keys: "git tag <tag-name>",
    platform: "Terminal",
  },
  {
    id: "git-53",
    app: "Git",
    category: "Tags",
    title: "Annotated Tag",
    description: "Create annotated tag",
    keys: 'git tag -a <tag-name> -m "msg"',
    platform: "Terminal",
  },
  {
    id: "git-54",
    app: "Git",
    category: "Tags",
    title: "Delete Tag",
    description: "Delete local tag",
    keys: "git tag -d <tag-name>",
    platform: "Terminal",
  },
  {
    id: "git-55",
    app: "Git",
    category: "Tags",
    title: "Show Tag",
    description: "Show tag details",
    keys: "git show <tag-name>",
    platform: "Terminal",
  },
  {
    id: "git-56",
    app: "Git",
    category: "Stash",
    title: "Stash Changes",
    description: "Save changes temporarily",
    keys: "git stash",
    platform: "Terminal",
  },
  {
    id: "git-57",
    app: "Git",
    category: "Stash",
    title: "Stash Named",
    description: "Stash with message",
    keys: 'git stash save "name"',
    platform: "Terminal",
  },
  {
    id: "git-58",
    app: "Git",
    category: "Stash",
    title: "List Stash",
    description: "Show stashed changes",
    keys: "git stash list",
    platform: "Terminal",
  },
  {
    id: "git-59",
    app: "Git",
    category: "Stash",
    title: "Pop Stash",
    description: "Apply and remove stash",
    keys: "git stash pop",
    platform: "Terminal",
  },
  {
    id: "git-60",
    app: "Git",
    category: "Stash",
    title: "Apply Stash",
    description: "Apply stash without removing",
    keys: "git stash apply <stash>",
    platform: "Terminal",
  },
  {
    id: "git-61",
    app: "Git",
    category: "Stash",
    title: "Drop Stash",
    description: "Delete stash",
    keys: "git stash drop <stash>",
    platform: "Terminal",
  },
  {
    id: "git-62",
    app: "Git",
    category: "Cleanup",
    title: "Clean Files",
    description: "Remove untracked files",
    keys: "git clean -fd",
    platform: "Terminal",
  },
  {
    id: "git-63",
    app: "Git",
    category: "Cleanup",
    title: "Reset Hard",
    description: "Reset to HEAD",
    keys: "git reset --hard HEAD",
    platform: "Terminal",
  },
  {
    id: "git-64",
    app: "Git",
    category: "Cleanup",
    title: "Reset Soft",
    description: "Reset keeping changes",
    keys: "git reset --soft HEAD~1",
    platform: "Terminal",
  },
  {
    id: "git-65",
    app: "Git",
    category: "Cleanup",
    title: "Reset Mixed",
    description: "Reset mixed mode",
    keys: "git reset --mixed <commit>",
    platform: "Terminal",
  },
  {
    id: "git-66",
    app: "Git",
    category: "Cleanup",
    title: "GC Garbage Collect",
    description: "Optimize repository",
    keys: "git gc",
    platform: "Terminal",
  },
  {
    id: "git-67",
    app: "Git",
    category: "Advanced",
    title: "Cherry Pick",
    description: "Apply specific commit",
    keys: "git cherry-pick <commit>",
    platform: "Terminal",
  },
  {
    id: "git-68",
    app: "Git",
    category: "Advanced",
    title: "Bisect Start",
    description: "Start binary search",
    keys: "git bisect start",
    platform: "Terminal",
  },
  {
    id: "git-69",
    app: "Git",
    category: "Advanced",
    title: "Reflog",
    description: "Show reference logs",
    keys: "git reflog",
    platform: "Terminal",
  },
  {
    id: "git-70",
    app: "Git",
    category: "Advanced",
    title: "Submodule",
    description: "Manage submodules",
    keys: "git submodule update",
    platform: "Terminal",
  },
  {
    id: "git-71",
    app: "Git",
    category: "Blame",
    title: "Blame File",
    description: "Show line history",
    keys: "git blame <file>",
    platform: "Terminal",
  },
  {
    id: "git-72",
    app: "Git",
    category: "Worktree",
    title: "Create Worktree",
    description: "Create work tree",
    keys: "git worktree add <path> <branch>",
    platform: "Terminal",
  },
  {
    id: "git-73",
    app: "Git",
    category: "Worktree",
    title: "List Worktrees",
    description: "Show worktrees",
    keys: "git worktree list",
    platform: "Terminal",
  },
  {
    id: "git-74",
    app: "Git",
    category: "Worktree",
    title: "Remove Worktree",
    description: "Delete worktree",
    keys: "git worktree remove <path>",
    platform: "Terminal",
  },
  {
    id: "git-75",
    app: "Git",
    category: "Hooks",
    title: "Pre-commit Hook",
    description: "Setup pre-commit",
    keys: "git hooks install",
    platform: "Terminal",
  },
  {
    id: "git-76",
    app: "Git",
    category: "Index",
    title: "Index Info",
    description: "Show index details",
    keys: "git ls-files",
    platform: "Terminal",
  },
  {
    id: "git-77",
    app: "Git",
    category: "Objects",
    title: "Show Objects",
    description: "List objects",
    keys: "git rev-list --all",
    platform: "Terminal",
  },
  {
    id: "git-78",
    app: "Git",
    category: "Patches",
    title: "Create Patch",
    description: "Generate patch file",
    keys: "git diff > file.patch",
    platform: "Terminal",
  },
  {
    id: "git-79",
    app: "Git",
    category: "Patches",
    title: "Apply Patch",
    description: "Apply patch file",
    keys: "git apply file.patch",
    platform: "Terminal",
  },
  {
    id: "git-80",
    app: "Git",
    category: "Patches",
    title: "Format Patch",
    description: "Create patch from commits",
    keys: "git format-patch <commit>",
    platform: "Terminal",
  },
  {
    id: "git-81",
    app: "Git",
    category: "Archive",
    title: "Create Archive",
    description: "Archive repository",
    keys: "git archive --format zip HEAD > repo.zip",
    platform: "Terminal",
  },
  {
    id: "git-82",
    app: "Git",
    category: "Search",
    title: "Grep Search",
    description: "Search in files",
    keys: "git grep <pattern>",
    platform: "Terminal",
  },
  {
    id: "git-83",
    app: "Git",
    category: "Search",
    title: "Log Search",
    description: "Search in commits",
    keys: "git log -S <text>",
    platform: "Terminal",
  },
  {
    id: "git-84",
    app: "Git",
    category: "Search",
    title: "Pick Search",
    description: "Search commits by regex",
    keys: "git log -p --grep=<regex>",
    platform: "Terminal",
  },
  {
    id: "git-85",
    app: "Git",
    category: "Sparse",
    title: "Sparse Checkout",
    description: "Partial repository",
    keys: "git sparse-checkout init",
    platform: "Terminal",
  },
  {
    id: "git-86",
    app: "Git",
    category: "Fsck",
    title: "File System Check",
    description: "Verify repository",
    keys: "git fsck",
    platform: "Terminal",
  },
  {
    id: "git-87",
    app: "Git",
    category: "Var",
    title: "Show Variables",
    description: "Show git variables",
    keys: "git var -l",
    platform: "Terminal",
  },
  {
    id: "git-88",
    app: "Git",
    category: "Notes",
    title: "Add Notes",
    description: "Add notes to commit",
    keys: 'git notes add -m "note"',
    platform: "Terminal",
  },
  {
    id: "git-89",
    app: "Git",
    category: "Notes",
    title: "Show Notes",
    description: "Show commit notes",
    keys: "git notes show",
    platform: "Terminal",
  },
  {
    id: "git-90",
    app: "Git",
    category: "Notes",
    title: "Remove Notes",
    description: "Remove notes",
    keys: "git notes remove",
    platform: "Terminal",
  },
  {
    id: "git-91",
    app: "Git",
    category: "Attributes",
    title: "Show Attributes",
    description: "Show file attributes",
    keys: "git check-attr -a <file>",
    platform: "Terminal",
  },
  {
    id: "git-92",
    app: "Git",
    category: "Hooks",
    title: "Update Hooks",
    description: "Update git hooks",
    keys: "git hooks update",
    platform: "Terminal",
  },
  {
    id: "git-93",
    app: "Git",
    category: "Ignore",
    title: "Check Ignored",
    description: "Check if file ignored",
    keys: "git check-ignore <file>",
    platform: "Terminal",
  },
  {
    id: "git-94",
    app: "Git",
    category: "Ignore",
    title: "Ignore Debug",
    description: "Debug gitignore",
    keys: "git check-ignore -v <file>",
    platform: "Terminal",
  },
  {
    id: "git-95",
    app: "Git",
    category: "Credential",
    title: "Approve Credential",
    description: "Approve credentials",
    keys: "git credential approve",
    platform: "Terminal",
  },
  {
    id: "git-96",
    app: "Git",
    category: "Credential",
    title: "Reject Credential",
    description: "Reject credentials",
    keys: "git credential reject",
    platform: "Terminal",
  },
  {
    id: "git-97",
    app: "Git",
    category: "Diff Tool",
    title: "Difftool",
    description: "Open diff tool",
    keys: "git difftool <file>",
    platform: "Terminal",
  },
  {
    id: "git-98",
    app: "Git",
    category: "Merge Tool",
    title: "Mergetool",
    description: "Open merge tool",
    keys: "git mergetool",
    platform: "Terminal",
  },
  {
    id: "git-99",
    app: "Git",
    category: "Version",
    title: "Git Version",
    description: "Show git version",
    keys: "git --version",
    platform: "Terminal",
  },
  {
    id: "git-100",
    app: "Git",
    category: "Help",
    title: "Git Help",
    description: "Show git help",
    keys: "git help <command>",
    platform: "Terminal",
  },

  // LINUX - 100+ shortcuts (terminal commands)
  {
    id: "linux-1",
    app: "Linux Terminal",
    category: "Navigation",
    title: "List Files",
    description: "List directory contents",
    keys: "ls",
    platform: "Terminal",
  },
  {
    id: "linux-2",
    app: "Linux Terminal",
    category: "Navigation",
    title: "List Detailed",
    description: "List with details",
    keys: "ls -la",
    platform: "Terminal",
  },
  {
    id: "linux-3",
    app: "Linux Terminal",
    category: "Navigation",
    title: "List Human Readable",
    description: "List with human sizes",
    keys: "ls -lh",
    platform: "Terminal",
  },
  {
    id: "linux-4",
    app: "Linux Terminal",
    category: "Navigation",
    title: "Change Directory",
    description: "Move to directory",
    keys: "cd <path>",
    platform: "Terminal",
  },
  {
    id: "linux-5",
    app: "Linux Terminal",
    category: "Navigation",
    title: "Go Home",
    description: "Go to home directory",
    keys: "cd ~",
    platform: "Terminal",
  },
  {
    id: "linux-6",
    app: "Linux Terminal",
    category: "Navigation",
    title: "Go Back",
    description: "Go to previous directory",
    keys: "cd -",
    platform: "Terminal",
  },
  {
    id: "linux-7",
    app: "Linux Terminal",
    category: "Navigation",
    title: "Print Working Directory",
    description: "Show current path",
    keys: "pwd",
    platform: "Terminal",
  },
  {
    id: "linux-8",
    app: "Linux Terminal",
    category: "Navigation",
    title: "Clear Screen",
    description: "Clear terminal",
    keys: "clear",
    platform: "Terminal",
  },
  {
    id: "linux-9",
    app: "Linux Terminal",
    category: "Files",
    title: "Create File",
    description: "Create empty file",
    keys: "touch <filename>",
    platform: "Terminal",
  },
  {
    id: "linux-10",
    app: "Linux Terminal",
    category: "Files",
    title: "Copy File",
    description: "Copy file",
    keys: "cp <source> <dest>",
    platform: "Terminal",
  },
  {
    id: "linux-11",
    app: "Linux Terminal",
    category: "Files",
    title: "Copy Recursive",
    description: "Copy directory recursively",
    keys: "cp -r <source> <dest>",
    platform: "Terminal",
  },
  {
    id: "linux-12",
    app: "Linux Terminal",
    category: "Files",
    title: "Move File",
    description: "Move/rename file",
    keys: "mv <source> <dest>",
    platform: "Terminal",
  },
  {
    id: "linux-13",
    app: "Linux Terminal",
    category: "Files",
    title: "Remove File",
    description: "Delete file",
    keys: "rm <file>",
    platform: "Terminal",
  },
  {
    id: "linux-14",
    app: "Linux Terminal",
    category: "Files",
    title: "Remove Force",
    description: "Force delete",
    keys: "rm -f <file>",
    platform: "Terminal",
  },
  {
    id: "linux-15",
    app: "Linux Terminal",
    category: "Files",
    title: "Remove Recursive",
    description: "Delete directory",
    keys: "rm -rf <directory>",
    platform: "Terminal",
  },
  {
    id: "linux-16",
    app: "Linux Terminal",
    category: "Directories",
    title: "Make Directory",
    description: "Create directory",
    keys: "mkdir <dirname>",
    platform: "Terminal",
  },
  {
    id: "linux-17",
    app: "Linux Terminal",
    category: "Directories",
    title: "Make Nested",
    description: "Create nested directories",
    keys: "mkdir -p <path>",
    platform: "Terminal",
  },
  {
    id: "linux-18",
    app: "Linux Terminal",
    category: "Directories",
    title: "Remove Directory",
    description: "Delete empty directory",
    keys: "rmdir <dirname>",
    platform: "Terminal",
  },
  {
    id: "linux-19",
    app: "Linux Terminal",
    category: "Directories",
    title: "Tree View",
    description: "Show directory tree",
    keys: "tree",
    platform: "Terminal",
  },
  {
    id: "linux-20",
    app: "Linux Terminal",
    category: "File Content",
    title: "View File",
    description: "Display file contents",
    keys: "cat <file>",
    platform: "Terminal",
  },
  {
    id: "linux-21",
    app: "Linux Terminal",
    category: "File Content",
    title: "View with Paging",
    description: "View file with pagination",
    keys: "less <file>",
    platform: "Terminal",
  },
  {
    id: "linux-22",
    app: "Linux Terminal",
    category: "File Content",
    title: "View Head",
    description: "Show first lines",
    keys: "head <file>",
    platform: "Terminal",
  },
  {
    id: "linux-23",
    app: "Linux Terminal",
    category: "File Content",
    title: "View Tail",
    description: "Show last lines",
    keys: "tail <file>",
    platform: "Terminal",
  },
  {
    id: "linux-24",
    app: "Linux Terminal",
    category: "File Content",
    title: "Tail Follow",
    description: "Follow file updates",
    keys: "tail -f <file>",
    platform: "Terminal",
  },
  {
    id: "linux-25",
    app: "Linux Terminal",
    category: "File Content",
    title: "Word Count",
    description: "Count lines/words",
    keys: "wc <file>",
    platform: "Terminal",
  },
  {
    id: "linux-26",
    app: "Linux Terminal",
    category: "Search",
    title: "Find Files",
    description: "Search for files",
    keys: "find <path> -name <pattern>",
    platform: "Terminal",
  },
  {
    id: "linux-27",
    app: "Linux Terminal",
    category: "Search",
    title: "Grep Search",
    description: "Search in files",
    keys: "grep <pattern> <file>",
    platform: "Terminal",
  },
  {
    id: "linux-28",
    app: "Linux Terminal",
    category: "Search",
    title: "Grep Recursive",
    description: "Search recursively",
    keys: "grep -r <pattern> <path>",
    platform: "Terminal",
  },
  {
    id: "linux-29",
    app: "Linux Terminal",
    category: "Search",
    title: "Grep Count",
    description: "Count matches",
    keys: "grep -c <pattern> <file>",
    platform: "Terminal",
  },
  {
    id: "linux-30",
    app: "Linux Terminal",
    category: "Search",
    title: "Locate File",
    description: "Locate file by name",
    keys: "locate <filename>",
    platform: "Terminal",
  },
  {
    id: "linux-31",
    app: "Linux Terminal",
    category: "Permissions",
    title: "Change Permissions",
    description: "Modify file permissions",
    keys: "chmod 755 <file>",
    platform: "Terminal",
  },
  {
    id: "linux-32",
    app: "Linux Terminal",
    category: "Permissions",
    title: "Change Owner",
    description: "Change file owner",
    keys: "chown <user> <file>",
    platform: "Terminal",
  },
  {
    id: "linux-33",
    app: "Linux Terminal",
    category: "Permissions",
    title: "Change Group",
    description: "Change file group",
    keys: "chgrp <group> <file>",
    platform: "Terminal",
  },
  {
    id: "linux-34",
    app: "Linux Terminal",
    category: "Permissions",
    title: "Recursive Permissions",
    description: "Change permissions recursively",
    keys: "chmod -R 755 <dir>",
    platform: "Terminal",
  },
  {
    id: "linux-35",
    app: "Linux Terminal",
    category: "Compression",
    title: "Create Tar",
    description: "Create tar archive",
    keys: "tar -cvf archive.tar <files>",
    platform: "Terminal",
  },
  {
    id: "linux-36",
    app: "Linux Terminal",
    category: "Compression",
    title: "Extract Tar",
    description: "Extract tar archive",
    keys: "tar -xvf archive.tar",
    platform: "Terminal",
  },
  {
    id: "linux-37",
    app: "Linux Terminal",
    category: "Compression",
    title: "Tar Gzip",
    description: "Create compressed tar",
    keys: "tar -czf archive.tar.gz <files>",
    platform: "Terminal",
  },
  {
    id: "linux-38",
    app: "Linux Terminal",
    category: "Compression",
    title: "Extract Gzip",
    description: "Extract gzip file",
    keys: "gunzip <file.gz>",
    platform: "Terminal",
  },
  {
    id: "linux-39",
    app: "Linux Terminal",
    category: "Compression",
    title: "Zip Files",
    description: "Create zip archive",
    keys: "zip -r archive.zip <files>",
    platform: "Terminal",
  },
  {
    id: "linux-40",
    app: "Linux Terminal",
    category: "Compression",
    title: "Unzip Files",
    description: "Extract zip archive",
    keys: "unzip archive.zip",
    platform: "Terminal",
  },
  {
    id: "linux-41",
    app: "Linux Terminal",
    category: "System",
    title: "System Info",
    description: "Show system information",
    keys: "uname -a",
    platform: "Terminal",
  },
  {
    id: "linux-42",
    app: "Linux Terminal",
    category: "System",
    title: "Disk Usage",
    description: "Show disk space",
    keys: "df -h",
    platform: "Terminal",
  },
  {
    id: "linux-43",
    app: "Linux Terminal",
    category: "System",
    title: "Directory Size",
    description: "Show directory size",
    keys: "du -sh <dir>",
    platform: "Terminal",
  },
  {
    id: "linux-44",
    app: "Linux Terminal",
    category: "System",
    title: "Memory Usage",
    description: "Show memory info",
    keys: "free -h",
    platform: "Terminal",
  },
  {
    id: "linux-45",
    app: "Linux Terminal",
    category: "System",
    title: "Process List",
    description: "Show running processes",
    keys: "ps aux",
    platform: "Terminal",
  },
  {
    id: "linux-46",
    app: "Linux Terminal",
    category: "System",
    title: "Top Processes",
    description: "Monitor processes",
    keys: "top",
    platform: "Terminal",
  },
  {
    id: "linux-47",
    app: "Linux Terminal",
    category: "System",
    title: "Kill Process",
    description: "Terminate process",
    keys: "kill <PID>",
    platform: "Terminal",
  },
  {
    id: "linux-48",
    app: "Linux Terminal",
    category: "System",
    title: "Force Kill",
    description: "Force terminate process",
    keys: "kill -9 <PID>",
    platform: "Terminal",
  },
  {
    id: "linux-49",
    app: "Linux Terminal",
    category: "System",
    title: "Uptime",
    description: "Show system uptime",
    keys: "uptime",
    platform: "Terminal",
  },
  {
    id: "linux-50",
    app: "Linux Terminal",
    category: "System",
    title: "Hostname",
    description: "Show hostname",
    keys: "hostname",
    platform: "Terminal",
  },
  {
    id: "linux-51",
    app: "Linux Terminal",
    category: "Users",
    title: "Current User",
    description: "Show current user",
    keys: "whoami",
    platform: "Terminal",
  },
  {
    id: "linux-52",
    app: "Linux Terminal",
    category: "Users",
    title: "Logged Users",
    description: "Show logged in users",
    keys: "who",
    platform: "Terminal",
  },
  {
    id: "linux-53",
    app: "Linux Terminal",
    category: "Users",
    title: "User ID",
    description: "Show user/group IDs",
    keys: "id",
    platform: "Terminal",
  },
  {
    id: "linux-54",
    app: "Linux Terminal",
    category: "Users",
    title: "Switch User",
    description: "Switch to another user",
    keys: "su <username>",
    platform: "Terminal",
  },
  {
    id: "linux-55",
    app: "Linux Terminal",
    category: "Users",
    title: "Sudo Command",
    description: "Run as superuser",
    keys: "sudo <command>",
    platform: "Terminal",
  },
  {
    id: "linux-56",
    app: "Linux Terminal",
    category: "Network",
    title: "IP Address",
    description: "Show IP configuration",
    keys: "ip addr",
    platform: "Terminal",
  },
  {
    id: "linux-57",
    app: "Linux Terminal",
    category: "Network",
    title: "Ping Host",
    description: "Test connectivity",
    keys: "ping <host>",
    platform: "Terminal",
  },
  {
    id: "linux-58",
    app: "Linux Terminal",
    category: "Network",
    title: "Traceroute",
    description: "Trace route to host",
    keys: "traceroute <host>",
    platform: "Terminal",
  },
  {
    id: "linux-59",
    app: "Linux Terminal",
    category: "Network",
    title: "DNS Lookup",
    description: "Lookup DNS records",
    keys: "nslookup <domain>",
    platform: "Terminal",
  },
  {
    id: "linux-60",
    app: "Linux Terminal",
    category: "Network",
    title: "Network Stats",
    description: "Show network statistics",
    keys: "netstat -an",
    platform: "Terminal",
  },
  {
    id: "linux-61",
    app: "Linux Terminal",
    category: "Network",
    title: "SSH Connect",
    description: "Connect via SSH",
    keys: "ssh <user>@<host>",
    platform: "Terminal",
  },
  {
    id: "linux-62",
    app: "Linux Terminal",
    category: "Network",
    title: "SCP Copy",
    description: "Copy via SSH",
    keys: "scp <file> <user>@<host>:<path>",
    platform: "Terminal",
  },
  {
    id: "linux-63",
    app: "Linux Terminal",
    category: "Network",
    title: "SFTP Connect",
    description: "Connect via SFTP",
    keys: "sftp <user>@<host>",
    platform: "Terminal",
  },
  {
    id: "linux-64",
    app: "Linux Terminal",
    category: "Network",
    title: "Wget Download",
    description: "Download file",
    keys: "wget <URL>",
    platform: "Terminal",
  },
  {
    id: "linux-65",
    app: "Linux Terminal",
    category: "Network",
    title: "Curl Request",
    description: "Make HTTP request",
    keys: "curl <URL>",
    platform: "Terminal",
  },
  {
    id: "linux-66",
    app: "Linux Terminal",
    category: "Package Manager",
    title: "Update Packages",
    description: "Update package list",
    keys: "apt update",
    platform: "Terminal",
  },
  {
    id: "linux-67",
    app: "Linux Terminal",
    category: "Package Manager",
    title: "Upgrade Packages",
    description: "Upgrade installed packages",
    keys: "apt upgrade",
    platform: "Terminal",
  },
  {
    id: "linux-68",
    app: "Linux Terminal",
    category: "Package Manager",
    title: "Install Package",
    description: "Install new package",
    keys: "apt install <package>",
    platform: "Terminal",
  },
  {
    id: "linux-69",
    app: "Linux Terminal",
    category: "Package Manager",
    title: "Remove Package",
    description: "Remove package",
    keys: "apt remove <package>",
    platform: "Terminal",
  },
  {
    id: "linux-70",
    app: "Linux Terminal",
    category: "Package Manager",
    title: "Search Package",
    description: "Search for package",
    keys: "apt search <package>",
    platform: "Terminal",
  },
  {
    id: "linux-71",
    app: "Linux Terminal",
    category: "Text Editors",
    title: "Nano Editor",
    description: "Open nano editor",
    keys: "nano <file>",
    platform: "Terminal",
  },
  {
    id: "linux-72",
    app: "Linux Terminal",
    category: "Text Editors",
    title: "Vim Editor",
    description: "Open vim editor",
    keys: "vim <file>",
    platform: "Terminal",
  },
  {
    id: "linux-73",
    app: "Linux Terminal",
    category: "Text Editors",
    title: "Vi Editor",
    description: "Open vi editor",
    keys: "vi <file>",
    platform: "Terminal",
  },
  {
    id: "linux-74",
    app: "Linux Terminal",
    category: "Text Editors",
    title: "Emacs Editor",
    description: "Open emacs editor",
    keys: "emacs <file>",
    platform: "Terminal",
  },
  {
    id: "linux-75",
    app: "Linux Terminal",
    category: "Pipes & Redirection",
    title: "Pipe Output",
    description: "Pipe command output",
    keys: "command1 | command2",
    platform: "Terminal",
  },
  {
    id: "linux-76",
    app: "Linux Terminal",
    category: "Pipes & Redirection",
    title: "Redirect Output",
    description: "Redirect to file",
    keys: "command > file.txt",
    platform: "Terminal",
  },
  {
    id: "linux-77",
    app: "Linux Terminal",
    category: "Pipes & Redirection",
    title: "Append Output",
    description: "Append to file",
    keys: "command >> file.txt",
    platform: "Terminal",
  },
  {
    id: "linux-78",
    app: "Linux Terminal",
    category: "Pipes & Redirection",
    title: "Redirect Error",
    description: "Redirect stderr",
    keys: "command 2> error.txt",
    platform: "Terminal",
  },
  {
    id: "linux-79",
    app: "Linux Terminal",
    category: "Pipes & Redirection",
    title: "Redirect Both",
    description: "Redirect stdout and stderr",
    keys: "command &> output.txt",
    platform: "Terminal",
  },
  {
    id: "linux-80",
    app: "Linux Terminal",
    category: "Pipes & Redirection",
    title: "Input Redirect",
    description: "Redirect input from file",
    keys: "command < input.txt",
    platform: "Terminal",
  },
  {
    id: "linux-81",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Execute Script",
    description: "Run shell script",
    keys: "bash script.sh",
    platform: "Terminal",
  },
  {
    id: "linux-82",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Make Executable",
    description: "Make script executable",
    keys: "chmod +x script.sh",
    platform: "Terminal",
  },
  {
    id: "linux-83",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Run Executable",
    description: "Run executable script",
    keys: "./script.sh",
    platform: "Terminal",
  },
  {
    id: "linux-84",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Background Process",
    description: "Run in background",
    keys: "command &",
    platform: "Terminal",
  },
  {
    id: "linux-85",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Foreground Process",
    description: "Bring to foreground",
    keys: "fg",
    platform: "Terminal",
  },
  {
    id: "linux-86",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Background Jobs",
    description: "List background jobs",
    keys: "jobs",
    platform: "Terminal",
  },
  {
    id: "linux-87",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Suspend Process",
    description: "Suspend current process",
    keys: "Ctrl + Z",
    platform: "Terminal",
  },
  {
    id: "linux-88",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Exit Terminal",
    description: "Exit shell",
    keys: "exit",
    platform: "Terminal",
  },
  {
    id: "linux-89",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Logout",
    description: "Logout from session",
    keys: "logout",
    platform: "Terminal",
  },
  {
    id: "linux-90",
    app: "Linux Terminal",
    category: "Scripting",
    title: "History",
    description: "Show command history",
    keys: "history",
    platform: "Terminal",
  },
  {
    id: "linux-91",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Clear History",
    description: "Clear command history",
    keys: "history -c",
    platform: "Terminal",
  },
  {
    id: "linux-92",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Repeat Command",
    description: "Repeat last command",
    keys: "!!",
    platform: "Terminal",
  },
  {
    id: "linux-93",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Last Argument",
    description: "Use last argument",
    keys: "!$",
    platform: "Terminal",
  },
  {
    id: "linux-94",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Search History",
    description: "Search command history",
    keys: "Ctrl + R",
    platform: "Terminal",
  },
  {
    id: "linux-95",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Alias Command",
    description: "Create command alias",
    keys: 'alias name="command"',
    platform: "Terminal",
  },
  {
    id: "linux-96",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Unalias",
    description: "Remove alias",
    keys: "unalias name",
    platform: "Terminal",
  },
  {
    id: "linux-97",
    app: "Linux Terminal",
    category: "Scripting",
    title: "List Aliases",
    description: "Show all aliases",
    keys: "alias",
    platform: "Terminal",
  },
  {
    id: "linux-98",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Environment Variables",
    description: "Show environment variables",
    keys: "env",
    platform: "Terminal",
  },
  {
    id: "linux-99",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Set Variable",
    description: "Set environment variable",
    keys: "export VAR=value",
    platform: "Terminal",
  },
  {
    id: "linux-100",
    app: "Linux Terminal",
    category: "Scripting",
    title: "Show Variable",
    description: "Display variable value",
    keys: "echo $VAR",
    platform: "Terminal",
  },
]

export function getUniqueApps(): string[] {
  return Array.from(new Set(shortcutsData.map((s) => s.app)))
}

export function getUniqueCategories(app?: string): string[] {
  const filtered = app ? shortcutsData.filter((s) => s.app === app) : shortcutsData
  return Array.from(new Set(filtered.map((s) => s.category)))
}

export function filterShortcuts(searchTerm = "", app?: string, category?: string): ShortcutItem[] {
  return shortcutsData.filter((item) => {
    const matchesSearch =
      searchTerm === "" ||
      item.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.description.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.keys.toLowerCase().includes(searchTerm.toLowerCase())

    const matchesApp = !app || item.app === app
    const matchesCategory = !category || item.category === category

    return matchesSearch && matchesApp && matchesCategory
  })
}
