export interface Shortcut {
  id: string
  app: string
  category: string
  name: string
  keys: string
  description: string
  platform?: "Windows" | "Mac" | "Linux" | "All"
}

export const SHORTCUTS_DATA: Shortcut[] = [
  // MS WORD - 100+ Shortcuts
  // File Operations
  {
    id: "w1",
    app: "MS Word",
    category: "File",
    name: "New Document",
    keys: "Ctrl + N",
    description: "Create a new document",
    platform: "All",
  },
  {
    id: "w2",
    app: "MS Word",
    category: "File",
    name: "Open Document",
    keys: "Ctrl + O",
    description: "Open an existing document",
    platform: "All",
  },
  {
    id: "w3",
    app: "MS Word",
    category: "File",
    name: "Save Document",
    keys: "Ctrl + S",
    description: "Save the current document",
    platform: "All",
  },
  {
    id: "w4",
    app: "MS Word",
    category: "File",
    name: "Save As",
    keys: "Ctrl + Shift + S",
    description: "Save with a new name or format",
    platform: "All",
  },
  {
    id: "w5",
    app: "MS Word",
    category: "File",
    name: "Print",
    keys: "Ctrl + P",
    description: "Open Print dialog",
    platform: "All",
  },
  {
    id: "w6",
    app: "MS Word",
    category: "File",
    name: "Close Document",
    keys: "Ctrl + W",
    description: "Close current document",
    platform: "All",
  },
  {
    id: "w7",
    app: "MS Word",
    category: "File",
    name: "Exit Word",
    keys: "Ctrl + Q",
    description: "Close Word application",
    platform: "All",
  },
  {
    id: "w8",
    app: "MS Word",
    category: "File",
    name: "Print Preview",
    keys: "Ctrl + Alt + I",
    description: "Preview before printing",
    platform: "All",
  },
  {
    id: "w9",
    app: "MS Word",
    category: "File",
    name: "Properties",
    keys: "Alt + F + I",
    description: "View document properties",
    platform: "All",
  },
  {
    id: "w10",
    app: "MS Word",
    category: "File",
    name: "Recent Documents",
    keys: "Ctrl + Tab",
    description: "Switch between recent docs",
    platform: "All",
  },

  // Editing
  {
    id: "w11",
    app: "MS Word",
    category: "Editing",
    name: "Undo",
    keys: "Ctrl + Z",
    description: "Undo last action",
    platform: "All",
  },
  {
    id: "w12",
    app: "MS Word",
    category: "Editing",
    name: "Redo",
    keys: "Ctrl + Y",
    description: "Redo last undone action",
    platform: "All",
  },
  {
    id: "w13",
    app: "MS Word",
    category: "Editing",
    name: "Cut",
    keys: "Ctrl + X",
    description: "Cut selected content",
    platform: "All",
  },
  {
    id: "w14",
    app: "MS Word",
    category: "Editing",
    name: "Copy",
    keys: "Ctrl + C",
    description: "Copy selected content",
    platform: "All",
  },
  {
    id: "w15",
    app: "MS Word",
    category: "Editing",
    name: "Paste",
    keys: "Ctrl + V",
    description: "Paste from clipboard",
    platform: "All",
  },
  {
    id: "w16",
    app: "MS Word",
    category: "Editing",
    name: "Paste Special",
    keys: "Ctrl + Shift + V",
    description: "Paste with options",
    platform: "All",
  },
  {
    id: "w17",
    app: "MS Word",
    category: "Editing",
    name: "Select All",
    keys: "Ctrl + A",
    description: "Select all content",
    platform: "All",
  },
  {
    id: "w18",
    app: "MS Word",
    category: "Editing",
    name: "Find",
    keys: "Ctrl + F",
    description: "Open Find dialog",
    platform: "All",
  },
  {
    id: "w19",
    app: "MS Word",
    category: "Editing",
    name: "Find & Replace",
    keys: "Ctrl + H",
    description: "Open Find & Replace dialog",
    platform: "All",
  },
  {
    id: "w20",
    app: "MS Word",
    category: "Editing",
    name: "Delete Word Forward",
    keys: "Ctrl + Del",
    description: "Delete word after cursor",
    platform: "All",
  },
  {
    id: "w21",
    app: "MS Word",
    category: "Editing",
    name: "Delete Word Back",
    keys: "Ctrl + Backspace",
    description: "Delete word before cursor",
    platform: "All",
  },
  {
    id: "w22",
    app: "MS Word",
    category: "Editing",
    name: "Extend Selection",
    keys: "Shift + End",
    description: "Select to end of line",
    platform: "All",
  },
  {
    id: "w23",
    app: "MS Word",
    category: "Editing",
    name: "Select Paragraph",
    keys: "Ctrl + Shift + End",
    description: "Select to end of document",
    platform: "All",
  },

  // Formatting
  {
    id: "w24",
    app: "MS Word",
    category: "Formatting",
    name: "Bold",
    keys: "Ctrl + B",
    description: "Make text bold",
    platform: "All",
  },
  {
    id: "w25",
    app: "MS Word",
    category: "Formatting",
    name: "Italic",
    keys: "Ctrl + I",
    description: "Make text italic",
    platform: "All",
  },
  {
    id: "w26",
    app: "MS Word",
    category: "Formatting",
    name: "Underline",
    keys: "Ctrl + U",
    description: "Underline text",
    platform: "All",
  },
  {
    id: "w27",
    app: "MS Word",
    category: "Formatting",
    name: "Double Underline",
    keys: "Ctrl + Shift + D",
    description: "Double underline text",
    platform: "All",
  },
  {
    id: "w28",
    app: "MS Word",
    category: "Formatting",
    name: "Strikethrough",
    keys: "Alt + Shift + 5",
    description: "Add strikethrough",
    platform: "All",
  },
  {
    id: "w29",
    app: "MS Word",
    category: "Formatting",
    name: "Subscript",
    keys: "Ctrl + =",
    description: "Make text subscript",
    platform: "All",
  },
  {
    id: "w30",
    app: "MS Word",
    category: "Formatting",
    name: "Superscript",
    keys: "Ctrl + Shift + +",
    description: "Make text superscript",
    platform: "All",
  },
  {
    id: "w31",
    app: "MS Word",
    category: "Formatting",
    name: "Clear Formatting",
    keys: "Ctrl + Space",
    description: "Remove all formatting",
    platform: "All",
  },
  {
    id: "w32",
    app: "MS Word",
    category: "Formatting",
    name: "Center Align",
    keys: "Ctrl + E",
    description: "Center text",
    platform: "All",
  },
  {
    id: "w33",
    app: "MS Word",
    category: "Formatting",
    name: "Left Align",
    keys: "Ctrl + L",
    description: "Left align text",
    platform: "All",
  },
  {
    id: "w34",
    app: "MS Word",
    category: "Formatting",
    name: "Right Align",
    keys: "Ctrl + R",
    description: "Right align text",
    platform: "All",
  },
  {
    id: "w35",
    app: "MS Word",
    category: "Formatting",
    name: "Justify",
    keys: "Ctrl + J",
    description: "Justify text",
    platform: "All",
  },
  {
    id: "w36",
    app: "MS Word",
    category: "Formatting",
    name: "Increase Font Size",
    keys: "Ctrl + ]",
    description: "Make text larger",
    platform: "All",
  },
  {
    id: "w37",
    app: "MS Word",
    category: "Formatting",
    name: "Decrease Font Size",
    keys: "Ctrl + [",
    description: "Make text smaller",
    platform: "All",
  },
  {
    id: "w38",
    app: "MS Word",
    category: "Formatting",
    name: "Change Case",
    keys: "Shift + F3",
    description: "Cycle through text cases",
    platform: "All",
  },
  {
    id: "w39",
    app: "MS Word",
    category: "Formatting",
    name: "Highlight",
    keys: "Ctrl + Alt + H",
    description: "Highlight text",
    platform: "All",
  },
  {
    id: "w40",
    app: "MS Word",
    category: "Formatting",
    name: "Font Color",
    keys: "Ctrl + Alt + F",
    description: "Change font color",
    platform: "All",
  },

  // Navigation
  {
    id: "w41",
    app: "MS Word",
    category: "Navigation",
    name: "Go to Beginning",
    keys: "Ctrl + Home",
    description: "Go to document start",
    platform: "All",
  },
  {
    id: "w42",
    app: "MS Word",
    category: "Navigation",
    name: "Go to End",
    keys: "Ctrl + End",
    description: "Go to document end",
    platform: "All",
  },
  {
    id: "w43",
    app: "MS Word",
    category: "Navigation",
    name: "Page Up",
    keys: "Page Up",
    description: "Move up one page",
    platform: "All",
  },
  {
    id: "w44",
    app: "MS Word",
    category: "Navigation",
    name: "Page Down",
    keys: "Page Down",
    description: "Move down one page",
    platform: "All",
  },
  {
    id: "w45",
    app: "MS Word",
    category: "Navigation",
    name: "Go to Page",
    keys: "Ctrl + G",
    description: "Navigate to specific page",
    platform: "All",
  },
  {
    id: "w46",
    app: "MS Word",
    category: "Navigation",
    name: "Next Word",
    keys: "Ctrl + Right",
    description: "Move to next word",
    platform: "All",
  },
  {
    id: "w47",
    app: "MS Word",
    category: "Navigation",
    name: "Previous Word",
    keys: "Ctrl + Left",
    description: "Move to previous word",
    platform: "All",
  },
  {
    id: "w48",
    app: "MS Word",
    category: "Navigation",
    name: "Line Start",
    keys: "Home",
    description: "Go to line start",
    platform: "All",
  },
  {
    id: "w49",
    app: "MS Word",
    category: "Navigation",
    name: "Line End",
    keys: "End",
    description: "Go to line end",
    platform: "All",
  },

  // Tables & Lists
  {
    id: "w50",
    app: "MS Word",
    category: "Tables",
    name: "Insert Table",
    keys: "Alt + A + T",
    description: "Insert a table",
    platform: "All",
  },
  {
    id: "w51",
    app: "MS Word",
    category: "Tables",
    name: "Tab in Table",
    keys: "Tab",
    description: "Move to next cell",
    platform: "All",
  },
  {
    id: "w52",
    app: "MS Word",
    category: "Tables",
    name: "Shift Tab in Table",
    keys: "Shift + Tab",
    description: "Move to previous cell",
    platform: "All",
  },
  {
    id: "w53",
    app: "MS Word",
    category: "Tables",
    name: "Row Below",
    keys: "Alt + A + I + B",
    description: "Insert row below",
    platform: "All",
  },
  {
    id: "w54",
    app: "MS Word",
    category: "Tables",
    name: "Bullet List",
    keys: "Ctrl + Shift + L",
    description: "Create bullet list",
    platform: "All",
  },
  {
    id: "w55",
    app: "MS Word",
    category: "Tables",
    name: "Numbered List",
    keys: "Ctrl + Shift + N",
    description: "Create numbered list",
    platform: "All",
  },
  {
    id: "w56",
    app: "MS Word",
    category: "Tables",
    name: "Increase Indent",
    keys: "Tab",
    description: "Increase list indent",
    platform: "All",
  },
  {
    id: "w57",
    app: "MS Word",
    category: "Tables",
    name: "Decrease Indent",
    keys: "Shift + Tab",
    description: "Decrease list indent",
    platform: "All",
  },

  // Styles & Headings
  {
    id: "w58",
    app: "MS Word",
    category: "Styles",
    name: "Heading 1",
    keys: "Ctrl + Alt + 1",
    description: "Apply Heading 1 style",
    platform: "All",
  },
  {
    id: "w59",
    app: "MS Word",
    category: "Styles",
    name: "Heading 2",
    keys: "Ctrl + Alt + 2",
    description: "Apply Heading 2 style",
    platform: "All",
  },
  {
    id: "w60",
    app: "MS Word",
    category: "Styles",
    name: "Heading 3",
    keys: "Ctrl + Alt + 3",
    description: "Apply Heading 3 style",
    platform: "All",
  },
  {
    id: "w61",
    app: "MS Word",
    category: "Styles",
    name: "Normal",
    keys: "Ctrl + Shift + N",
    description: "Apply Normal style",
    platform: "All",
  },
  {
    id: "w62",
    app: "MS Word",
    category: "Styles",
    name: "Open Style Pane",
    keys: "Ctrl + Alt + Shift + S",
    description: "Open Styles sidebar",
    platform: "All",
  },
  {
    id: "w63",
    app: "MS Word",
    category: "Styles",
    name: "Repeat Last",
    keys: "Ctrl + Y",
    description: "Repeat last action",
    platform: "All",
  },

  // Advanced Features
  {
    id: "w64",
    app: "MS Word",
    category: "Advanced",
    name: "Insert Comment",
    keys: "Ctrl + Alt + M",
    description: "Insert a comment",
    platform: "All",
  },
  {
    id: "w65",
    app: "MS Word",
    category: "Advanced",
    name: "Track Changes",
    keys: "Ctrl + Shift + E",
    description: "Toggle Track Changes",
    platform: "All",
  },
  {
    id: "w66",
    app: "MS Word",
    category: "Advanced",
    name: "Accept Change",
    keys: "Ctrl + Shift + A",
    description: "Accept tracked change",
    platform: "All",
  },
  {
    id: "w67",
    app: "MS Word",
    category: "Advanced",
    name: "Insert Footnote",
    keys: "Ctrl + Alt + F",
    description: "Insert footnote",
    platform: "All",
  },
  {
    id: "w68",
    app: "MS Word",
    category: "Advanced",
    name: "Insert Endnote",
    keys: "Ctrl + Alt + E",
    description: "Insert endnote",
    platform: "All",
  },
  {
    id: "w69",
    app: "MS Word",
    category: "Advanced",
    name: "Insert Page Break",
    keys: "Ctrl + Enter",
    description: "Insert page break",
    platform: "All",
  },
  {
    id: "w70",
    app: "MS Word",
    category: "Advanced",
    name: "Insert Column Break",
    keys: "Ctrl + Shift + Enter",
    description: "Insert column break",
    platform: "All",
  },
  {
    id: "w71",
    app: "MS Word",
    category: "Advanced",
    name: "Insert Hyperlink",
    keys: "Ctrl + K",
    description: "Insert or edit hyperlink",
    platform: "All",
  },
  {
    id: "w72",
    app: "MS Word",
    category: "Advanced",
    name: "Create Citation",
    keys: "Ctrl + Shift + Alt + C",
    description: "Create citation reference",
    platform: "All",
  },
  {
    id: "w73",
    app: "MS Word",
    category: "Advanced",
    name: "Insert Symbol",
    keys: "Alt + I + S",
    description: "Insert special symbols",
    platform: "All",
  },
  {
    id: "w74",
    app: "MS Word",
    category: "Advanced",
    name: "Insert Table of Contents",
    keys: "Alt + T + C",
    description: "Generate TOC",
    platform: "All",
  },
  {
    id: "w75",
    app: "MS Word",
    category: "Advanced",
    name: "Field Dialog",
    keys: "Ctrl + F9",
    description: "Insert field code",
    platform: "All",
  },
  {
    id: "w76",
    app: "MS Word",
    category: "Advanced",
    name: "Date",
    keys: "Alt + Shift + D",
    description: "Insert current date",
    platform: "All",
  },
  {
    id: "w77",
    app: "MS Word",
    category: "Advanced",
    name: "Time",
    keys: "Alt + Shift + T",
    description: "Insert current time",
    platform: "All",
  },
  {
    id: "w78",
    app: "MS Word",
    category: "Advanced",
    name: "Page Number",
    keys: "Alt + Shift + P",
    description: "Insert page number",
    platform: "All",
  },
  {
    id: "w79",
    app: "MS Word",
    category: "Advanced",
    name: "Word Count",
    keys: "Ctrl + Shift + C",
    description: "Show word count",
    platform: "All",
  },
  {
    id: "w80",
    app: "MS Word",
    category: "Advanced",
    name: "Spelling & Grammar",
    keys: "F7",
    description: "Check spelling",
    platform: "All",
  },
  {
    id: "w81",
    app: "MS Word",
    category: "Advanced",
    name: "Thesaurus",
    keys: "Shift + F7",
    description: "Open thesaurus",
    platform: "All",
  },
  {
    id: "w82",
    app: "MS Word",
    category: "Advanced",
    name: "Language",
    keys: "Ctrl + Alt + L",
    description: "Set language",
    platform: "All",
  },
  {
    id: "w83",
    app: "MS Word",
    category: "Advanced",
    name: "Research Pane",
    keys: "Ctrl + Alt + R",
    description: "Open research sidebar",
    platform: "All",
  },
  {
    id: "w84",
    app: "MS Word",
    category: "Advanced",
    name: "Lock Track Changes",
    keys: "Ctrl + Shift + Alt + E",
    description: "Lock all changes",
    platform: "All",
  },

  // Excel - 100+ Shortcuts
  // File Operations
  {
    id: "e1",
    app: "MS Excel",
    category: "File",
    name: "New Workbook",
    keys: "Ctrl + N",
    description: "Create new workbook",
    platform: "All",
  },
  {
    id: "e2",
    app: "MS Excel",
    category: "File",
    name: "Open",
    keys: "Ctrl + O",
    description: "Open workbook",
    platform: "All",
  },
  {
    id: "e3",
    app: "MS Excel",
    category: "File",
    name: "Save",
    keys: "Ctrl + S",
    description: "Save workbook",
    platform: "All",
  },
  {
    id: "e4",
    app: "MS Excel",
    category: "File",
    name: "Save As",
    keys: "Ctrl + Shift + S",
    description: "Save with new name",
    platform: "All",
  },
  {
    id: "e5",
    app: "MS Excel",
    category: "File",
    name: "Print",
    keys: "Ctrl + P",
    description: "Print workbook",
    platform: "All",
  },
  {
    id: "e6",
    app: "MS Excel",
    category: "File",
    name: "Close Workbook",
    keys: "Ctrl + W",
    description: "Close current workbook",
    platform: "All",
  },
  {
    id: "e7",
    app: "MS Excel",
    category: "File",
    name: "Exit Excel",
    keys: "Ctrl + Q",
    description: "Close Excel",
    platform: "All",
  },
  {
    id: "e8",
    app: "MS Excel",
    category: "File",
    name: "Print Preview",
    keys: "Ctrl + Alt + I",
    description: "Preview before print",
    platform: "All",
  },

  // Navigation & Selection
  {
    id: "e9",
    app: "MS Excel",
    category: "Navigation",
    name: "Go To",
    keys: "Ctrl + G",
    description: "Open Go To dialog",
    platform: "All",
  },
  {
    id: "e10",
    app: "MS Excel",
    category: "Navigation",
    name: "Go To Special",
    keys: "Ctrl + Shift + G",
    description: "Go to special cells",
    platform: "All",
  },
  {
    id: "e11",
    app: "MS Excel",
    category: "Navigation",
    name: "Begin Cell",
    keys: "Ctrl + Home",
    description: "Go to cell A1",
    platform: "All",
  },
  {
    id: "e12",
    app: "MS Excel",
    category: "Navigation",
    name: "End of Data",
    keys: "Ctrl + End",
    description: "Go to last used cell",
    platform: "All",
  },
  {
    id: "e13",
    app: "MS Excel",
    category: "Navigation",
    name: "Page Down",
    keys: "Page Down",
    description: "Move down one screen",
    platform: "All",
  },
  {
    id: "e14",
    app: "MS Excel",
    category: "Navigation",
    name: "Page Up",
    keys: "Page Up",
    description: "Move up one screen",
    platform: "All",
  },
  {
    id: "e15",
    app: "MS Excel",
    category: "Navigation",
    name: "Right One Column",
    keys: "Right Arrow",
    description: "Move right",
    platform: "All",
  },
  {
    id: "e16",
    app: "MS Excel",
    category: "Navigation",
    name: "Left One Column",
    keys: "Left Arrow",
    description: "Move left",
    platform: "All",
  },
  {
    id: "e17",
    app: "MS Excel",
    category: "Navigation",
    name: "Next Sheet",
    keys: "Ctrl + Page Down",
    description: "Go to next sheet",
    platform: "All",
  },
  {
    id: "e18",
    app: "MS Excel",
    category: "Navigation",
    name: "Previous Sheet",
    keys: "Ctrl + Page Up",
    description: "Go to previous sheet",
    platform: "All",
  },
  {
    id: "e19",
    app: "MS Excel",
    category: "Navigation",
    name: "New Sheet",
    keys: "Alt + Shift + F1",
    description: "Insert new sheet",
    platform: "All",
  },
  {
    id: "e20",
    app: "MS Excel",
    category: "Navigation",
    name: "Select Column",
    keys: "Ctrl + Space",
    description: "Select entire column",
    platform: "All",
  },
  {
    id: "e21",
    app: "MS Excel",
    category: "Navigation",
    name: "Select Row",
    keys: "Shift + Space",
    description: "Select entire row",
    platform: "All",
  },
  {
    id: "e22",
    app: "MS Excel",
    category: "Navigation",
    name: "Select All",
    keys: "Ctrl + A",
    description: "Select all cells",
    platform: "All",
  },
  {
    id: "e23",
    app: "MS Excel",
    category: "Navigation",
    name: "Extend Selection",
    keys: "Shift + Click",
    description: "Extend selection",
    platform: "All",
  },

  // Editing
  {
    id: "e24",
    app: "MS Excel",
    category: "Editing",
    name: "Undo",
    keys: "Ctrl + Z",
    description: "Undo last action",
    platform: "All",
  },
  {
    id: "e25",
    app: "MS Excel",
    category: "Editing",
    name: "Redo",
    keys: "Ctrl + Y",
    description: "Redo action",
    platform: "All",
  },
  {
    id: "e26",
    app: "MS Excel",
    category: "Editing",
    name: "Cut",
    keys: "Ctrl + X",
    description: "Cut cells",
    platform: "All",
  },
  {
    id: "e27",
    app: "MS Excel",
    category: "Editing",
    name: "Copy",
    keys: "Ctrl + C",
    description: "Copy cells",
    platform: "All",
  },
  {
    id: "e28",
    app: "MS Excel",
    category: "Editing",
    name: "Paste",
    keys: "Ctrl + V",
    description: "Paste cells",
    platform: "All",
  },
  {
    id: "e29",
    app: "MS Excel",
    category: "Editing",
    name: "Paste Special",
    keys: "Ctrl + Shift + V",
    description: "Paste with options",
    platform: "All",
  },
  {
    id: "e30",
    app: "MS Excel",
    category: "Editing",
    name: "Find",
    keys: "Ctrl + F",
    description: "Open Find dialog",
    platform: "All",
  },
  {
    id: "e31",
    app: "MS Excel",
    category: "Editing",
    name: "Find & Replace",
    keys: "Ctrl + H",
    description: "Find and replace",
    platform: "All",
  },
  {
    id: "e32",
    app: "MS Excel",
    category: "Editing",
    name: "Clear Contents",
    keys: "Delete",
    description: "Delete cell content",
    platform: "All",
  },
  {
    id: "e33",
    app: "MS Excel",
    category: "Editing",
    name: "Delete Cell",
    keys: "Ctrl + -",
    description: "Delete cells",
    platform: "All",
  },
  {
    id: "e34",
    app: "MS Excel",
    category: "Editing",
    name: "Insert Cells",
    keys: "Ctrl + +",
    description: "Insert cells",
    platform: "All",
  },
  {
    id: "e35",
    app: "MS Excel",
    category: "Editing",
    name: "Edit Cell",
    keys: "F2",
    description: "Edit active cell",
    platform: "All",
  },
  {
    id: "e36",
    app: "MS Excel",
    category: "Editing",
    name: "Enter Cell",
    keys: "Enter",
    description: "Complete entry",
    platform: "All",
  },
  {
    id: "e37",
    app: "MS Excel",
    category: "Editing",
    name: "Tab to Next",
    keys: "Tab",
    description: "Move to next cell",
    platform: "All",
  },

  // Formatting
  {
    id: "e38",
    app: "MS Excel",
    category: "Formatting",
    name: "Bold",
    keys: "Ctrl + B",
    description: "Make bold",
    platform: "All",
  },
  {
    id: "e39",
    app: "MS Excel",
    category: "Formatting",
    name: "Italic",
    keys: "Ctrl + I",
    description: "Make italic",
    platform: "All",
  },
  {
    id: "e40",
    app: "MS Excel",
    category: "Formatting",
    name: "Underline",
    keys: "Ctrl + U",
    description: "Underline text",
    platform: "All",
  },
  {
    id: "e41",
    app: "MS Excel",
    category: "Formatting",
    name: "Strikethrough",
    keys: "Alt + Shift + 5",
    description: "Strikethrough",
    platform: "All",
  },
  {
    id: "e42",
    app: "MS Excel",
    category: "Formatting",
    name: "Format Cells",
    keys: "Ctrl + 1",
    description: "Open format dialog",
    platform: "All",
  },
  {
    id: "e43",
    app: "MS Excel",
    category: "Formatting",
    name: "Align Left",
    keys: "Ctrl + L",
    description: "Left align",
    platform: "All",
  },
  {
    id: "e44",
    app: "MS Excel",
    category: "Formatting",
    name: "Align Center",
    keys: "Ctrl + E",
    description: "Center align",
    platform: "All",
  },
  {
    id: "e45",
    app: "MS Excel",
    category: "Formatting",
    name: "Align Right",
    keys: "Ctrl + R",
    description: "Right align",
    platform: "All",
  },
  {
    id: "e46",
    app: "MS Excel",
    category: "Formatting",
    name: "Currency",
    keys: "Ctrl + Shift + 4",
    description: "Currency format",
    platform: "All",
  },
  {
    id: "e47",
    app: "MS Excel",
    category: "Formatting",
    name: "Percentage",
    keys: "Ctrl + Shift + 5",
    description: "Percentage format",
    platform: "All",
  },
  {
    id: "e48",
    app: "MS Excel",
    category: "Formatting",
    name: "Date Format",
    keys: "Ctrl + Shift + 3",
    description: "Date format",
    platform: "All",
  },
  {
    id: "e49",
    app: "MS Excel",
    category: "Formatting",
    name: "Time Format",
    keys: "Ctrl + Shift + 2",
    description: "Time format",
    platform: "All",
  },
  {
    id: "e50",
    app: "MS Excel",
    category: "Formatting",
    name: "Number Format",
    keys: "Ctrl + Shift + 1",
    description: "Number format",
    platform: "All",
  },
  {
    id: "e51",
    app: "MS Excel",
    category: "Formatting",
    name: "Borders",
    keys: "Alt + H + B",
    description: "Add borders",
    platform: "All",
  },
  {
    id: "e52",
    app: "MS Excel",
    category: "Formatting",
    name: "Fill Color",
    keys: "Alt + H + H",
    description: "Fill background color",
    platform: "All",
  },
  {
    id: "e53",
    app: "MS Excel",
    category: "Formatting",
    name: "Font Color",
    keys: "Alt + H + F + C",
    description: "Change font color",
    platform: "All",
  },

  // Formulas & Data
  {
    id: "e54",
    app: "MS Excel",
    category: "Formulas",
    name: "Sum",
    keys: "Alt + =",
    description: "Insert SUM formula",
    platform: "All",
  },
  {
    id: "e55",
    app: "MS Excel",
    category: "Formulas",
    name: "AutoSum",
    keys: "Alt + Shift + =",
    description: "Quick sum",
    platform: "All",
  },
  {
    id: "e56",
    app: "MS Excel",
    category: "Formulas",
    name: "Function Wizard",
    keys: "Shift + F3",
    description: "Open function wizard",
    platform: "All",
  },
  {
    id: "e57",
    app: "MS Excel",
    category: "Formulas",
    name: "Absolute Reference",
    keys: "F4",
    description: "Toggle absolute reference",
    platform: "All",
  },
  {
    id: "e58",
    app: "MS Excel",
    category: "Formulas",
    name: "Array Formula",
    keys: "Ctrl + Shift + Enter",
    description: "Create array formula",
    platform: "All",
  },
  {
    id: "e59",
    app: "MS Excel",
    category: "Formulas",
    name: "Show Formulas",
    keys: "Ctrl + `",
    description: "Toggle formula view",
    platform: "All",
  },
  {
    id: "e60",
    app: "MS Excel",
    category: "Formulas",
    name: "Formula Auditing",
    keys: "Ctrl + Shift + F9",
    description: "Recalculate all",
    platform: "All",
  },
  {
    id: "e61",
    app: "MS Excel",
    category: "Formulas",
    name: "IF Formula",
    keys: "Type: =IF()",
    description: "Conditional formula",
    platform: "All",
  },
  {
    id: "e62",
    app: "MS Excel",
    category: "Formulas",
    name: "VLOOKUP",
    keys: "Type: =VLOOKUP()",
    description: "Vertical lookup",
    platform: "All",
  },
  {
    id: "e63",
    app: "MS Excel",
    category: "Formulas",
    name: "HLOOKUP",
    keys: "Type: =HLOOKUP()",
    description: "Horizontal lookup",
    platform: "All",
  },
  {
    id: "e64",
    app: "MS Excel",
    category: "Formulas",
    name: "INDEX MATCH",
    keys: "Type: =INDEX(MATCH())",
    description: "Combined lookup",
    platform: "All",
  },
  {
    id: "e65",
    app: "MS Excel",
    category: "Formulas",
    name: "CONCATENATE",
    keys: "Type: =CONCATENATE()",
    description: "Combine text",
    platform: "All",
  },
  {
    id: "e66",
    app: "MS Excel",
    category: "Formulas",
    name: "COUNTIF",
    keys: "Type: =COUNTIF()",
    description: "Conditional count",
    platform: "All",
  },
  {
    id: "e67",
    app: "MS Excel",
    category: "Formulas",
    name: "SUMIF",
    keys: "Type: =SUMIF()",
    description: "Conditional sum",
    platform: "All",
  },
  {
    id: "e68",
    app: "MS Excel",
    category: "Formulas",
    name: "AVERAGEIF",
    keys: "Type: =AVERAGEIF()",
    description: "Conditional average",
    platform: "All",
  },
  {
    id: "e69",
    app: "MS Excel",
    category: "Formulas",
    name: "PIVOT TABLE",
    keys: "Alt + D + P",
    description: "Create pivot table",
    platform: "All",
  },
  {
    id: "e70",
    app: "MS Excel",
    category: "Formulas",
    name: "Data Validation",
    keys: "Alt + D + L",
    description: "Add data validation",
    platform: "All",
  },
  {
    id: "e71",
    app: "MS Excel",
    category: "Formulas",
    name: "Sort",
    keys: "Alt + D + S",
    description: "Sort data",
    platform: "All",
  },
  {
    id: "e72",
    app: "MS Excel",
    category: "Formulas",
    name: "Filter",
    keys: "Ctrl + Shift + L",
    description: "Add auto filter",
    platform: "All",
  },
  {
    id: "e73",
    app: "MS Excel",
    category: "Formulas",
    name: "Subtotal",
    keys: "Alt + D + B",
    description: "Insert subtotals",
    platform: "All",
  },

  // Advanced
  {
    id: "e74",
    app: "MS Excel",
    category: "Advanced",
    name: "Goal Seek",
    keys: "Alt + T + G",
    description: "Goal seek feature",
    platform: "All",
  },
  {
    id: "e75",
    app: "MS Excel",
    category: "Advanced",
    name: "Solver",
    keys: "Alt + T + S",
    description: "Solver tool",
    platform: "All",
  },
  {
    id: "e76",
    app: "MS Excel",
    category: "Advanced",
    name: "Data Table",
    keys: "Alt + D + T",
    description: "Create data table",
    platform: "All",
  },
  {
    id: "e77",
    app: "MS Excel",
    category: "Advanced",
    name: "Scenario Manager",
    keys: "Alt + T + Z",
    description: "Manage scenarios",
    platform: "All",
  },
  {
    id: "e78",
    app: "MS Excel",
    category: "Advanced",
    name: "Macro",
    keys: "Alt + F8",
    description: "Record/run macro",
    platform: "All",
  },
  {
    id: "e79",
    app: "MS Excel",
    category: "Advanced",
    name: "Sheet Protect",
    keys: "Alt + T + P + P",
    description: "Protect sheet",
    platform: "All",
  },
  {
    id: "e80",
    app: "MS Excel",
    category: "Advanced",
    name: "Workbook Protect",
    keys: "Alt + T + P + W",
    description: "Protect workbook",
    platform: "All",
  },
  {
    id: "e81",
    app: "MS Excel",
    category: "Advanced",
    name: "Freeze Panes",
    keys: "Alt + W + F + F",
    description: "Freeze panes",
    platform: "All",
  },
  {
    id: "e82",
    app: "MS Excel",
    category: "Advanced",
    name: "Split Window",
    keys: "Alt + W + I",
    description: "Split window",
    platform: "All",
  },
  {
    id: "e83",
    app: "MS Excel",
    category: "Advanced",
    name: "Zoom",
    keys: "Ctrl + Mouse Wheel",
    description: "Zoom in/out",
    platform: "All",
  },
  {
    id: "e84",
    app: "MS Excel",
    category: "Advanced",
    name: "Insert Chart",
    keys: "Alt + I + C",
    description: "Insert chart",
    platform: "All",
  },
  {
    id: "e85",
    app: "MS Excel",
    category: "Advanced",
    name: "Conditional Format",
    keys: "Alt + H + L",
    description: "Conditional formatting",
    platform: "All",
  },
  {
    id: "e86",
    app: "MS Excel",
    category: "Advanced",
    name: "Clear Direct Format",
    keys: "Ctrl + M",
    description: "Clear formatting",
    platform: "All",
  },

  // VS CODE - 100+ Shortcuts
  {
    id: "v1",
    app: "VS Code",
    category: "File",
    name: "New File",
    keys: "Ctrl + N",
    description: "Create new file",
    platform: "All",
  },
  {
    id: "v2",
    app: "VS Code",
    category: "File",
    name: "Open File",
    keys: "Ctrl + O",
    description: "Open file",
    platform: "All",
  },
  {
    id: "v3",
    app: "VS Code",
    category: "File",
    name: "Open Folder",
    keys: "Ctrl + K Ctrl + O",
    description: "Open folder",
    platform: "All",
  },
  {
    id: "v4",
    app: "VS Code",
    category: "File",
    name: "Save",
    keys: "Ctrl + S",
    description: "Save file",
    platform: "All",
  },
  {
    id: "v5",
    app: "VS Code",
    category: "File",
    name: "Save All",
    keys: "Ctrl + Alt + S",
    description: "Save all files",
    platform: "All",
  },
  {
    id: "v6",
    app: "VS Code",
    category: "File",
    name: "Quick Open",
    keys: "Ctrl + P",
    description: "Quick file opener",
    platform: "All",
  },
  {
    id: "v7",
    app: "VS Code",
    category: "File",
    name: "Recent Files",
    keys: "Ctrl + Tab",
    description: "Switch recent files",
    platform: "All",
  },
  {
    id: "v8",
    app: "VS Code",
    category: "File",
    name: "Close Tab",
    keys: "Ctrl + W",
    description: "Close editor tab",
    platform: "All",
  },
  {
    id: "v9",
    app: "VS Code",
    category: "File",
    name: "Close Folder",
    keys: "Ctrl + K F",
    description: "Close folder",
    platform: "All",
  },
  {
    id: "v10",
    app: "VS Code",
    category: "File",
    name: "Close All",
    keys: "Ctrl + Shift + W",
    description: "Close all tabs",
    platform: "All",
  },
  {
    id: "v11",
    app: "VS Code",
    category: "File",
    name: "Revert File",
    keys: "Ctrl + K U",
    description: "Revert file changes",
    platform: "All",
  },
  {
    id: "v12",
    app: "VS Code",
    category: "File",
    name: "Split Editor",
    keys: "Ctrl + \\",
    description: "Split editor view",
    platform: "All",
  },
  {
    id: "v13",
    app: "VS Code",
    category: "File",
    name: "Focus on Editor",
    keys: "Ctrl + 1",
    description: "Focus editor group 1",
    platform: "All",
  },
  {
    id: "v14",
    app: "VS Code",
    category: "File",
    name: "Focus on Side",
    keys: "Ctrl + 0",
    description: "Focus sidebar",
    platform: "All",
  },
  {
    id: "v15",
    app: "VS Code",
    category: "File",
    name: "Exit VS Code",
    keys: "Ctrl + Shift + Q",
    description: "Close VS Code",
    platform: "All",
  },

  // Editing
  {
    id: "v16",
    app: "VS Code",
    category: "Editing",
    name: "Undo",
    keys: "Ctrl + Z",
    description: "Undo",
    platform: "All",
  },
  {
    id: "v17",
    app: "VS Code",
    category: "Editing",
    name: "Redo",
    keys: "Ctrl + Y",
    description: "Redo",
    platform: "All",
  },
  {
    id: "v18",
    app: "VS Code",
    category: "Editing",
    name: "Cut Line",
    keys: "Ctrl + X",
    description: "Cut entire line",
    platform: "All",
  },
  {
    id: "v19",
    app: "VS Code",
    category: "Editing",
    name: "Copy Line",
    keys: "Ctrl + C",
    description: "Copy line",
    platform: "All",
  },
  {
    id: "v20",
    app: "VS Code",
    category: "Editing",
    name: "Paste",
    keys: "Ctrl + V",
    description: "Paste",
    platform: "All",
  },
  {
    id: "v21",
    app: "VS Code",
    category: "Editing",
    name: "Select All",
    keys: "Ctrl + A",
    description: "Select all",
    platform: "All",
  },
  {
    id: "v22",
    app: "VS Code",
    category: "Editing",
    name: "Find",
    keys: "Ctrl + F",
    description: "Find in file",
    platform: "All",
  },
  {
    id: "v23",
    app: "VS Code",
    category: "Editing",
    name: "Replace",
    keys: "Ctrl + H",
    description: "Find and replace",
    platform: "All",
  },
  {
    id: "v24",
    app: "VS Code",
    category: "Editing",
    name: "Find in Files",
    keys: "Ctrl + Shift + F",
    description: "Search across files",
    platform: "All",
  },
  {
    id: "v25",
    app: "VS Code",
    category: "Editing",
    name: "Replace in Files",
    keys: "Ctrl + Shift + H",
    description: "Replace across files",
    platform: "All",
  },
  {
    id: "v26",
    app: "VS Code",
    category: "Editing",
    name: "Delete Line",
    keys: "Ctrl + Shift + K",
    description: "Delete entire line",
    platform: "All",
  },
  {
    id: "v27",
    app: "VS Code",
    category: "Editing",
    name: "Duplicate Line",
    keys: "Ctrl + D",
    description: "Duplicate line",
    platform: "All",
  },
  {
    id: "v28",
    app: "VS Code",
    category: "Editing",
    name: "Move Line Up",
    keys: "Alt + Up",
    description: "Move line up",
    platform: "All",
  },
  {
    id: "v29",
    app: "VS Code",
    category: "Editing",
    name: "Move Line Down",
    keys: "Alt + Down",
    description: "Move line down",
    platform: "All",
  },
  {
    id: "v30",
    app: "VS Code",
    category: "Editing",
    name: "Insert Line Below",
    keys: "Ctrl + Enter",
    description: "Insert line below",
    platform: "All",
  },
  {
    id: "v31",
    app: "VS Code",
    category: "Editing",
    name: "Insert Line Above",
    keys: "Ctrl + Shift + Enter",
    description: "Insert line above",
    platform: "All",
  },
  {
    id: "v32",
    app: "VS Code",
    category: "Editing",
    name: "Jump to Line",
    keys: "Ctrl + G",
    description: "Go to specific line",
    platform: "All",
  },
  {
    id: "v33",
    app: "VS Code",
    category: "Editing",
    name: "Indent Line",
    keys: "Tab",
    description: "Indent line",
    platform: "All",
  },
  {
    id: "v34",
    app: "VS Code",
    category: "Editing",
    name: "Outdent Line",
    keys: "Shift + Tab",
    description: "Outdent line",
    platform: "All",
  },
  {
    id: "v35",
    app: "VS Code",
    category: "Editing",
    name: "Format Document",
    keys: "Shift + Alt + F",
    description: "Auto format",
    platform: "All",
  },
  {
    id: "v36",
    app: "VS Code",
    category: "Editing",
    name: "Format Selection",
    keys: "Ctrl + K Ctrl + F",
    description: "Format selection",
    platform: "All",
  },
  {
    id: "v37",
    app: "VS Code",
    category: "Editing",
    name: "Go to Definition",
    keys: "Ctrl + Click",
    description: "Jump to definition",
    platform: "All",
  },
  {
    id: "v38",
    app: "VS Code",
    category: "Editing",
    name: "Peek Definition",
    keys: "Ctrl + Shift + F10",
    description: "Peek definition",
    platform: "All",
  },
  {
    id: "v39",
    app: "VS Code",
    category: "Editing",
    name: "Toggle Comment",
    keys: "Ctrl + /",
    description: "Comment line",
    platform: "All",
  },
  {
    id: "v40",
    app: "VS Code",
    category: "Editing",
    name: "Block Comment",
    keys: "Shift + Alt + A",
    description: "Block comment",
    platform: "All",
  },
  {
    id: "v41",
    app: "VS Code",
    category: "Editing",
    name: "Column Select",
    keys: "Shift + Alt + Click",
    description: "Columnar selection",
    platform: "All",
  },
  {
    id: "v42",
    app: "VS Code",
    category: "Editing",
    name: "Multi-Cursor",
    keys: "Ctrl + Alt + Up/Down",
    description: "Add cursor up/down",
    platform: "All",
  },
  {
    id: "v43",
    app: "VS Code",
    category: "Editing",
    name: "Add Cursor",
    keys: "Ctrl + Click",
    description: "Add cursor at click",
    platform: "All",
  },
  {
    id: "v44",
    app: "VS Code",
    category: "Editing",
    name: "Select Word",
    keys: "Ctrl + D",
    description: "Select word",
    platform: "All",
  },
  {
    id: "v45",
    app: "VS Code",
    category: "Editing",
    name: "Expand Selection",
    keys: "Ctrl + Shift + Right",
    description: "Expand selection",
    platform: "All",
  },
  {
    id: "v46",
    app: "VS Code",
    category: "Editing",
    name: "Shrink Selection",
    keys: "Ctrl + Shift + Left",
    description: "Shrink selection",
    platform: "All",
  },
  {
    id: "v47",
    app: "VS Code",
    category: "Editing",
    name: "Convert to Uppercase",
    keys: "Ctrl + Shift + U",
    description: "Uppercase",
    platform: "All",
  },
  {
    id: "v48",
    app: "VS Code",
    category: "Editing",
    name: "Convert to Lowercase",
    keys: "Ctrl + Shift + L",
    description: "Lowercase",
    platform: "All",
  },
  {
    id: "v49",
    app: "VS Code",
    category: "Editing",
    name: "Rename Symbol",
    keys: "F2",
    description: "Rename variable",
    platform: "All",
  },
  {
    id: "v50",
    app: "VS Code",
    category: "Editing",
    name: "Sort Lines",
    keys: "F9",
    description: "Sort selected lines",
    platform: "All",
  },

  // Navigation
  {
    id: "v51",
    app: "VS Code",
    category: "Navigation",
    name: "Command Palette",
    keys: "Ctrl + Shift + P",
    description: "Open command palette",
    platform: "All",
  },
  {
    id: "v52",
    app: "VS Code",
    category: "Navigation",
    name: "Go to File",
    keys: "Ctrl + P",
    description: "Quick file jump",
    platform: "All",
  },
  {
    id: "v53",
    app: "VS Code",
    category: "Navigation",
    name: "Go to Symbol",
    keys: "Ctrl + Shift + O",
    description: "Jump to symbol",
    platform: "All",
  },
  {
    id: "v54",
    app: "VS Code",
    category: "Navigation",
    name: "Global Symbol Search",
    keys: "Ctrl + T",
    description: "Search all symbols",
    platform: "All",
  },
  {
    id: "v55",
    app: "VS Code",
    category: "Navigation",
    name: "Go to Line",
    keys: "Ctrl + G",
    description: "Jump to line",
    platform: "All",
  },
  {
    id: "v56",
    app: "VS Code",
    category: "Navigation",
    name: "Go to Bracket",
    keys: "Ctrl + Shift + \\",
    description: "Jump to bracket",
    platform: "All",
  },
  {
    id: "v57",
    app: "VS Code",
    category: "Navigation",
    name: "Breadcrumb",
    keys: "Ctrl + Shift + .",
    description: "Show breadcrumb",
    platform: "All",
  },
  {
    id: "v58",
    app: "VS Code",
    category: "Navigation",
    name: "Back Navigation",
    keys: "Alt + Left",
    description: "Navigate back",
    platform: "All",
  },
  {
    id: "v59",
    app: "VS Code",
    category: "Navigation",
    name: "Forward Navigation",
    keys: "Alt + Right",
    description: "Navigate forward",
    platform: "All",
  },
  {
    id: "v60",
    app: "VS Code",
    category: "Navigation",
    name: "Focus Explorer",
    keys: "Ctrl + Shift + E",
    description: "Focus file explorer",
    platform: "All",
  },
  {
    id: "v61",
    app: "VS Code",
    category: "Navigation",
    name: "Focus Search",
    keys: "Ctrl + Shift + F",
    description: "Focus search",
    platform: "All",
  },
  {
    id: "v62",
    app: "VS Code",
    category: "Navigation",
    name: "Focus SCM",
    keys: "Ctrl + Shift + G",
    description: "Focus source control",
    platform: "All",
  },
  {
    id: "v63",
    app: "VS Code",
    category: "Navigation",
    name: "Focus Run",
    keys: "Ctrl + Shift + D",
    description: "Focus run and debug",
    platform: "All",
  },
  {
    id: "v64",
    app: "VS Code",
    category: "Navigation",
    name: "Focus Extensions",
    keys: "Ctrl + Shift + X",
    description: "Focus extensions",
    platform: "All",
  },
  {
    id: "v65",
    app: "VS Code",
    category: "Navigation",
    name: "Terminal",
    keys: "Ctrl + `",
    description: "Toggle terminal",
    platform: "All",
  },
  {
    id: "v66",
    app: "VS Code",
    category: "Navigation",
    name: "Problems",
    keys: "Ctrl + Shift + M",
    description: "Show problems",
    platform: "All",
  },
  {
    id: "v67",
    app: "VS Code",
    category: "Navigation",
    name: "Output",
    keys: "Ctrl + Shift + U",
    description: "Show output",
    platform: "All",
  },
  {
    id: "v68",
    app: "VS Code",
    category: "Navigation",
    name: "Debug Console",
    keys: "Ctrl + Shift + Y",
    description: "Show debug console",
    platform: "All",
  },
  {
    id: "v69",
    app: "VS Code",
    category: "Navigation",
    name: "Zen Mode",
    keys: "Ctrl + K Z",
    description: "Toggle zen mode",
    platform: "All",
  },
  {
    id: "v70",
    app: "VS Code",
    category: "Navigation",
    name: "Full Screen",
    keys: "F11",
    description: "Toggle fullscreen",
    platform: "All",
  },

  // GIT & GITHUB - 100+ Shortcuts
  {
    id: "g1",
    app: "Git",
    category: "Staging",
    name: "Stage Changes",
    keys: "git add .",
    description: "Stage all changes",
    platform: "All",
  },
  {
    id: "g2",
    app: "Git",
    category: "Staging",
    name: "Stage File",
    keys: "git add <file>",
    description: "Stage specific file",
    platform: "All",
  },
  {
    id: "g3",
    app: "Git",
    category: "Staging",
    name: "Unstage Changes",
    keys: "git reset HEAD",
    description: "Unstage all",
    platform: "All",
  },
  {
    id: "g4",
    app: "Git",
    category: "Staging",
    name: "Unstage File",
    keys: "git reset <file>",
    description: "Unstage file",
    platform: "All",
  },
  {
    id: "g5",
    app: "Git",
    category: "Staging",
    name: "Stage Interactive",
    keys: "git add -p",
    description: "Stage by patch",
    platform: "All",
  },
  {
    id: "g6",
    app: "Git",
    category: "Staging",
    name: "Check Status",
    keys: "git status",
    description: "Show git status",
    platform: "All",
  },
  {
    id: "g7",
    app: "Git",
    category: "Staging",
    name: "Check Diff",
    keys: "git diff",
    description: "Show unstaged changes",
    platform: "All",
  },
  {
    id: "g8",
    app: "Git",
    category: "Staging",
    name: "DiffCached",
    keys: "git diff --cached",
    description: "Show staged changes",
    platform: "All",
  },
  {
    id: "g9",
    app: "Git",
    category: "Staging",
    name: "Discard Changes",
    keys: "git checkout -- .",
    description: "Discard all changes",
    platform: "All",
  },
  {
    id: "g10",
    app: "Git",
    category: "Staging",
    name: "Discard File",
    keys: "git checkout -- <file>",
    description: "Discard file changes",
    platform: "All",
  },

  {
    id: "g11",
    app: "Git",
    category: "Commits",
    name: "Commit",
    keys: 'git commit -m "msg"',
    description: "Create commit",
    platform: "All",
  },
  {
    id: "g12",
    app: "Git",
    category: "Commits",
    name: "Commit All",
    keys: 'git commit -am "msg"',
    description: "Stage and commit",
    platform: "All",
  },
  {
    id: "g13",
    app: "Git",
    category: "Commits",
    name: "Amend Commit",
    keys: "git commit --amend",
    description: "Modify last commit",
    platform: "All",
  },
  {
    id: "g14",
    app: "Git",
    category: "Commits",
    name: "View Log",
    keys: "git log",
    description: "Show commit history",
    platform: "All",
  },
  {
    id: "g15",
    app: "Git",
    category: "Commits",
    name: "Log One Line",
    keys: "git log --oneline",
    description: "Compact log view",
    platform: "All",
  },
  {
    id: "g16",
    app: "Git",
    category: "Commits",
    name: "Log Graph",
    keys: "git log --graph --all",
    description: "Visual branch graph",
    platform: "All",
  },
  {
    id: "g17",
    app: "Git",
    category: "Commits",
    name: "Show Commit",
    keys: "git show <commit>",
    description: "Show commit details",
    platform: "All",
  },
  {
    id: "g18",
    app: "Git",
    category: "Commits",
    name: "Revert Commit",
    keys: "git revert <commit>",
    description: "Revert commit",
    platform: "All",
  },
  {
    id: "g19",
    app: "Git",
    category: "Commits",
    name: "Reset Soft",
    keys: "git reset --soft HEAD~1",
    description: "Soft reset",
    platform: "All",
  },
  {
    id: "g20",
    app: "Git",
    category: "Commits",
    name: "Reset Hard",
    keys: "git reset --hard HEAD~1",
    description: "Hard reset",
    platform: "All",
  },

  {
    id: "g21",
    app: "Git",
    category: "Branches",
    name: "List Branches",
    keys: "git branch",
    description: "Show branches",
    platform: "All",
  },
  {
    id: "g22",
    app: "Git",
    category: "Branches",
    name: "List Remote",
    keys: "git branch -r",
    description: "Show remote branches",
    platform: "All",
  },
  {
    id: "g23",
    app: "Git",
    category: "Branches",
    name: "Create Branch",
    keys: "git branch <name>",
    description: "Create new branch",
    platform: "All",
  },
  {
    id: "g24",
    app: "Git",
    category: "Branches",
    name: "Checkout Branch",
    keys: "git checkout <branch>",
    description: "Switch branch",
    platform: "All",
  },
  {
    id: "g25",
    app: "Git",
    category: "Branches",
    name: "Create Checkout",
    keys: "git checkout -b <branch>",
    description: "Create and switch branch",
    platform: "All",
  },
  {
    id: "g26",
    app: "Git",
    category: "Branches",
    name: "Delete Branch",
    keys: "git branch -d <branch>",
    description: "Delete branch",
    platform: "All",
  },
  {
    id: "g27",
    app: "Git",
    category: "Branches",
    name: "Force Delete",
    keys: "git branch -D <branch>",
    description: "Force delete",
    platform: "All",
  },
  {
    id: "g28",
    app: "Git",
    category: "Branches",
    name: "Rename Branch",
    keys: "git branch -m <new>",
    description: "Rename branch",
    platform: "All",
  },
  {
    id: "g29",
    app: "Git",
    category: "Branches",
    name: "Merge Branch",
    keys: "git merge <branch>",
    description: "Merge branch",
    platform: "All",
  },
  {
    id: "g30",
    app: "Git",
    category: "Branches",
    name: "Merge Squash",
    keys: "git merge --squash",
    description: "Squash commits",
    platform: "All",
  },

  {
    id: "g31",
    app: "Git",
    category: "Remotes",
    name: "Show Remotes",
    keys: "git remote",
    description: "List remotes",
    platform: "All",
  },
  {
    id: "g32",
    app: "Git",
    category: "Remotes",
    name: "Remote Details",
    keys: "git remote -v",
    description: "Show remote URLs",
    platform: "All",
  },
  {
    id: "g33",
    app: "Git",
    category: "Remotes",
    name: "Add Remote",
    keys: "git remote add <name> <url>",
    description: "Add remote",
    platform: "All",
  },
  {
    id: "g34",
    app: "Git",
    category: "Remotes",
    name: "Remove Remote",
    keys: "git remote remove <name>",
    description: "Remove remote",
    platform: "All",
  },
  {
    id: "g35",
    app: "Git",
    category: "Remotes",
    name: "Push",
    keys: "git push",
    description: "Push commits",
    platform: "All",
  },
  {
    id: "g36",
    app: "Git",
    category: "Remotes",
    name: "Push Branch",
    keys: "git push -u origin <branch>",
    description: "Push with tracking",
    platform: "All",
  },
  {
    id: "g37",
    app: "Git",
    category: "Remotes",
    name: "Pull",
    keys: "git pull",
    description: "Fetch and merge",
    platform: "All",
  },
  {
    id: "g38",
    app: "Git",
    category: "Remotes",
    name: "Fetch",
    keys: "git fetch",
    description: "Fetch updates",
    platform: "All",
  },
  {
    id: "g39",
    app: "Git",
    category: "Remotes",
    name: "Push Delete",
    keys: "git push origin --delete <branch>",
    description: "Delete remote branch",
    platform: "All",
  },
  {
    id: "g40",
    app: "Git",
    category: "Remotes",
    name: "Force Push",
    keys: "git push -f",
    description: "Force push",
    platform: "All",
  },

  // LINUX - 100+ Shortcuts
  {
    id: "l1",
    app: "Linux Terminal",
    category: "Navigation",
    name: "List Files",
    keys: "ls",
    description: "List directory contents",
    platform: "Linux",
  },
  {
    id: "l2",
    app: "Linux Terminal",
    category: "Navigation",
    name: "List Long",
    keys: "ls -la",
    description: "Long format listing",
    platform: "Linux",
  },
  {
    id: "l3",
    app: "Linux Terminal",
    category: "Navigation",
    name: "Current Directory",
    keys: "pwd",
    description: "Print working directory",
    platform: "Linux",
  },
  {
    id: "l4",
    app: "Linux Terminal",
    category: "Navigation",
    name: "Change Directory",
    keys: "cd <path>",
    description: "Change directory",
    platform: "Linux",
  },
  {
    id: "l5",
    app: "Linux Terminal",
    category: "Navigation",
    name: "Home Directory",
    keys: "cd ~",
    description: "Go to home",
    platform: "Linux",
  },
  {
    id: "l6",
    app: "Linux Terminal",
    category: "Navigation",
    name: "Parent Directory",
    keys: "cd ..",
    description: "Go up one level",
    platform: "Linux",
  },
  {
    id: "l7",
    app: "Linux Terminal",
    category: "Navigation",
    name: "Last Directory",
    keys: "cd -",
    description: "Go to last directory",
    platform: "Linux",
  },
  {
    id: "l8",
    app: "Linux Terminal",
    category: "Navigation",
    name: "Clear Screen",
    keys: "clear",
    description: "Clear terminal",
    platform: "Linux",
  },
  {
    id: "l9",
    app: "Linux Terminal",
    category: "Navigation",
    name: "Tree View",
    keys: "tree",
    description: "Show directory tree",
    platform: "Linux",
  },
  {
    id: "l10",
    app: "Linux Terminal",
    category: "Navigation",
    name: "Find File",
    keys: "find . -name <name>",
    description: "Find files",
    platform: "Linux",
  },

  {
    id: "l11",
    app: "Linux Terminal",
    category: "Files",
    name: "Create File",
    keys: "touch <file>",
    description: "Create empty file",
    platform: "Linux",
  },
  {
    id: "l12",
    app: "Linux Terminal",
    category: "Files",
    name: "Create Directory",
    keys: "mkdir <dir>",
    description: "Create directory",
    platform: "Linux",
  },
  {
    id: "l13",
    app: "Linux Terminal",
    category: "Files",
    name: "Copy File",
    keys: "cp <src> <dst>",
    description: "Copy file",
    platform: "Linux",
  },
  {
    id: "l14",
    app: "Linux Terminal",
    category: "Files",
    name: "Copy Recursive",
    keys: "cp -r <src> <dst>",
    description: "Copy directory",
    platform: "Linux",
  },
  {
    id: "l15",
    app: "Linux Terminal",
    category: "Files",
    name: "Move File",
    keys: "mv <src> <dst>",
    description: "Move/rename file",
    platform: "Linux",
  },
  {
    id: "l16",
    app: "Linux Terminal",
    category: "Files",
    name: "Remove File",
    keys: "rm <file>",
    description: "Delete file",
    platform: "Linux",
  },
  {
    id: "l17",
    app: "Linux Terminal",
    category: "Files",
    name: "Remove Directory",
    keys: "rm -rf <dir>",
    description: "Delete directory",
    platform: "Linux",
  },
  {
    id: "l18",
    app: "Linux Terminal",
    category: "Files",
    name: "View File",
    keys: "cat <file>",
    description: "Display file content",
    platform: "Linux",
  },
  {
    id: "l19",
    app: "Linux Terminal",
    category: "Files",
    name: "Search Text",
    keys: "grep <text> <file>",
    description: "Search in file",
    platform: "Linux",
  },
  {
    id: "l20",
    app: "Linux Terminal",
    category: "Files",
    name: "Line Count",
    keys: "wc -l <file>",
    description: "Count lines",
    platform: "Linux",
  },

  {
    id: "l21",
    app: "Linux Terminal",
    category: "Permissions",
    name: "Change Permissions",
    keys: "chmod 755 <file>",
    description: "Change file permissions",
    platform: "Linux",
  },
  {
    id: "l22",
    app: "Linux Terminal",
    category: "Permissions",
    name: "Change Owner",
    keys: "chown <user> <file>",
    description: "Change ownership",
    platform: "Linux",
  },
  {
    id: "l23",
    app: "Linux Terminal",
    category: "Permissions",
    name: "Make Executable",
    keys: "chmod +x <file>",
    description: "Make executable",
    platform: "Linux",
  },
  {
    id: "l24",
    app: "Linux Terminal",
    category: "Permissions",
    name: "Add Read",
    keys: "chmod +r <file>",
    description: "Add read permission",
    platform: "Linux",
  },
  {
    id: "l25",
    app: "Linux Terminal",
    category: "Permissions",
    name: "Add Write",
    keys: "chmod +w <file>",
    description: "Add write permission",
    platform: "Linux",
  },

  {
    id: "l26",
    app: "Linux Terminal",
    category: "System",
    name: "Disk Usage",
    keys: "df -h",
    description: "Show disk space",
    platform: "Linux",
  },
  {
    id: "l27",
    app: "Linux Terminal",
    category: "System",
    name: "Directory Size",
    keys: "du -sh <dir>",
    description: "Directory size",
    platform: "Linux",
  },
  {
    id: "l28",
    app: "Linux Terminal",
    category: "System",
    name: "Process List",
    keys: "ps aux",
    description: "List processes",
    platform: "Linux",
  },
  {
    id: "l29",
    app: "Linux Terminal",
    category: "System",
    name: "Memory Usage",
    keys: "free -h",
    description: "Show memory",
    platform: "Linux",
  },
  {
    id: "l30",
    app: "Linux Terminal",
    category: "System",
    name: "System Info",
    keys: "uname -a",
    description: "System information",
    platform: "Linux",
  },
  {
    id: "l31",
    app: "Linux Terminal",
    category: "System",
    name: "Uptime",
    keys: "uptime",
    description: "System uptime",
    platform: "Linux",
  },
  {
    id: "l32",
    app: "Linux Terminal",
    category: "System",
    name: "Current User",
    keys: "whoami",
    description: "Current user",
    platform: "Linux",
  },
  {
    id: "l33",
    app: "Linux Terminal",
    category: "System",
    name: "User Groups",
    keys: "groups",
    description: "List user groups",
    platform: "Linux",
  },
  {
    id: "l34",
    app: "Linux Terminal",
    category: "System",
    name: "Who Logged In",
    keys: "who",
    description: "Show logged in users",
    platform: "Linux",
  },
  {
    id: "l35",
    app: "Linux Terminal",
    category: "System",
    name: "Last Login",
    keys: "last",
    description: "Last login info",
    platform: "Linux",
  },

  {
    id: "l36",
    app: "Linux Terminal",
    category: "Networking",
    name: "IP Address",
    keys: "ip addr show",
    description: "Show IP addresses",
    platform: "Linux",
  },
  {
    id: "l37",
    app: "Linux Terminal",
    category: "Networking",
    name: "Hostname",
    keys: "hostname",
    description: "Show hostname",
    platform: "Linux",
  },
  {
    id: "l38",
    app: "Linux Terminal",
    category: "Networking",
    name: "Ping Host",
    keys: "ping <host>",
    description: "Test connectivity",
    platform: "Linux",
  },
  {
    id: "l39",
    app: "Linux Terminal",
    category: "Networking",
    name: "Network Config",
    keys: "ifconfig",
    description: "Network configuration",
    platform: "Linux",
  },
  {
    id: "l40",
    app: "Linux Terminal",
    category: "Networking",
    name: "Trace Route",
    keys: "traceroute <host>",
    description: "Trace route to host",
    platform: "Linux",
  },
  {
    id: "l41",
    app: "Linux Terminal",
    category: "Networking",
    name: "DNS Lookup",
    keys: "nslookup <domain>",
    description: "DNS lookup",
    platform: "Linux",
  },
  {
    id: "l42",
    app: "Linux Terminal",
    category: "Networking",
    name: "Netstat",
    keys: "netstat -an",
    description: "Network statistics",
    platform: "Linux",
  },
  {
    id: "l43",
    app: "Linux Terminal",
    category: "Networking",
    name: "Show Routes",
    keys: "route -n",
    description: "Show routing table",
    platform: "Linux",
  },
  {
    id: "l44",
    app: "Linux Terminal",
    category: "Networking",
    name: "SSH Connect",
    keys: "ssh user@host",
    description: "SSH connection",
    platform: "Linux",
  },
  {
    id: "l45",
    app: "Linux Terminal",
    category: "Networking",
    name: "SCP Copy",
    keys: "scp <file> user@host:",
    description: "Secure copy",
    platform: "Linux",
  },

  {
    id: "l46",
    app: "Linux Terminal",
    category: "Package Manager",
    name: "Install Package",
    keys: "apt install <pkg>",
    description: "Install package",
    platform: "Linux",
  },
  {
    id: "l47",
    app: "Linux Terminal",
    category: "Package Manager",
    name: "Remove Package",
    keys: "apt remove <pkg>",
    description: "Remove package",
    platform: "Linux",
  },
  {
    id: "l48",
    app: "Linux Terminal",
    category: "Package Manager",
    name: "Update Packages",
    keys: "apt update",
    description: "Update package list",
    platform: "Linux",
  },
  {
    id: "l49",
    app: "Linux Terminal",
    category: "Package Manager",
    name: "Upgrade Packages",
    keys: "apt upgrade",
    description: "Upgrade packages",
    platform: "Linux",
  },
  {
    id: "l50",
    app: "Linux Terminal",
    category: "Package Manager",
    name: "Search Package",
    keys: "apt search <pkg>",
    description: "Search package",
    platform: "Linux",
  },

  // PYTHON/JUPYTER - 100+ Shortcuts
  {
    id: "j1",
    app: "Jupyter Notebook",
    category: "Navigation",
    name: "Run Cell",
    keys: "Ctrl + Enter",
    description: "Execute current cell",
    platform: "All",
  },
  {
    id: "j2",
    app: "Jupyter Notebook",
    category: "Navigation",
    name: "Run & Next",
    keys: "Shift + Enter",
    description: "Run and move to next",
    platform: "All",
  },
  {
    id: "j3",
    app: "Jupyter Notebook",
    category: "Navigation",
    name: "Next Cell",
    keys: "Down Arrow",
    description: "Move to next cell",
    platform: "All",
  },
  {
    id: "j4",
    app: "Jupyter Notebook",
    category: "Navigation",
    name: "Previous Cell",
    keys: "Up Arrow",
    description: "Move to previous cell",
    platform: "All",
  },
  {
    id: "j5",
    app: "Jupyter Notebook",
    category: "Navigation",
    name: "First Cell",
    keys: "Ctrl + Home",
    description: "Go to first cell",
    platform: "All",
  },
  {
    id: "j6",
    app: "Jupyter Notebook",
    category: "Navigation",
    name: "Last Cell",
    keys: "Ctrl + End",
    description: "Go to last cell",
    platform: "All",
  },
  {
    id: "j7",
    app: "Jupyter Notebook",
    category: "Navigation",
    name: "Focus Cell",
    keys: "Enter",
    description: "Enter edit mode",
    platform: "All",
  },
  {
    id: "j8",
    app: "Jupyter Notebook",
    category: "Navigation",
    name: "Unfocus Cell",
    keys: "Escape",
    description: "Exit edit mode",
    platform: "All",
  },
  {
    id: "j9",
    app: "Jupyter Notebook",
    category: "Navigation",
    name: "Scroll Down",
    keys: "Page Down",
    description: "Page down",
    platform: "All",
  },
  {
    id: "j10",
    app: "Jupyter Notebook",
    category: "Navigation",
    name: "Scroll Up",
    keys: "Page Up",
    description: "Page up",
    platform: "All",
  },

  {
    id: "j11",
    app: "Jupyter Notebook",
    category: "Cells",
    name: "Insert Below",
    keys: "B",
    description: "Insert cell below",
    platform: "All",
  },
  {
    id: "j12",
    app: "Jupyter Notebook",
    category: "Cells",
    name: "Insert Above",
    keys: "A",
    description: "Insert cell above",
    platform: "All",
  },
  {
    id: "j13",
    app: "Jupyter Notebook",
    category: "Cells",
    name: "Delete Cell",
    keys: "D D",
    description: "Delete cell",
    platform: "All",
  },
  {
    id: "j14",
    app: "Jupyter Notebook",
    category: "Cells",
    name: "Cut Cell",
    keys: "X",
    description: "Cut cell",
    platform: "All",
  },
  {
    id: "j15",
    app: "Jupyter Notebook",
    category: "Cells",
    name: "Copy Cell",
    keys: "C",
    description: "Copy cell",
    platform: "All",
  },
  {
    id: "j16",
    app: "Jupyter Notebook",
    category: "Cells",
    name: "Paste Below",
    keys: "V",
    description: "Paste below",
    platform: "All",
  },
  {
    id: "j17",
    app: "Jupyter Notebook",
    category: "Cells",
    name: "Undo Delete",
    keys: "Z",
    description: "Undo delete",
    platform: "All",
  },
  {
    id: "j18",
    app: "Jupyter Notebook",
    category: "Cells",
    name: "Merge Cells",
    keys: "Shift + M",
    description: "Merge with next",
    platform: "All",
  },
  {
    id: "j19",
    app: "Jupyter Notebook",
    category: "Cells",
    name: "Split Cell",
    keys: "Ctrl + Shift + -",
    description: "Split cell",
    platform: "All",
  },
  {
    id: "j20",
    app: "Jupyter Notebook",
    category: "Cells",
    name: "Move Up",
    keys: "Ctrl + Shift + Up",
    description: "Move cell up",
    platform: "All",
  },

  {
    id: "j21",
    app: "Jupyter Notebook",
    category: "Cell Type",
    name: "Code Cell",
    keys: "Y",
    description: "Change to code",
    platform: "All",
  },
  {
    id: "j22",
    app: "Jupyter Notebook",
    category: "Cell Type",
    name: "Markdown Cell",
    keys: "M",
    description: "Change to markdown",
    platform: "All",
  },
  {
    id: "j23",
    app: "Jupyter Notebook",
    category: "Cell Type",
    name: "Raw Cell",
    keys: "R",
    description: "Change to raw",
    platform: "All",
  },
  {
    id: "j24",
    app: "Jupyter Notebook",
    category: "Cell Type",
    name: "Heading 1",
    keys: "Ctrl + Alt + 1",
    description: "Insert heading 1",
    platform: "All",
  },
  {
    id: "j25",
    app: "Jupyter Notebook",
    category: "Cell Type",
    name: "Heading 2",
    keys: "Ctrl + Alt + 2",
    description: "Insert heading 2",
    platform: "All",
  },

  {
    id: "j26",
    app: "Jupyter Notebook",
    category: "Kernel",
    name: "Interrupt Kernel",
    keys: "I I",
    description: "Stop execution",
    platform: "All",
  },
  {
    id: "j27",
    app: "Jupyter Notebook",
    category: "Kernel",
    name: "Restart Kernel",
    keys: "0 0",
    description: "Restart kernel",
    platform: "All",
  },
  {
    id: "j28",
    app: "Jupyter Notebook",
    category: "Kernel",
    name: "Clear Output",
    keys: "Shift + O",
    description: "Clear all output",
    platform: "All",
  },
  {
    id: "j29",
    app: "Jupyter Notebook",
    category: "Kernel",
    name: "Run All",
    keys: "Ctrl + Shift + Enter",
    description: "Run all cells",
    platform: "All",
  },
  {
    id: "j30",
    app: "Jupyter Notebook",
    category: "Kernel",
    name: "Run Below",
    keys: "Alt + Enter",
    description: "Run from here down",
    platform: "All",
  },

  {
    id: "j31",
    app: "Python",
    category: "Basics",
    name: "Print",
    keys: "print()",
    description: "Print statement",
    platform: "All",
  },
  {
    id: "j32",
    app: "Python",
    category: "Basics",
    name: "Variable",
    keys: "var = value",
    description: "Variable assignment",
    platform: "All",
  },
  {
    id: "j33",
    app: "Python",
    category: "Basics",
    name: "List",
    keys: "[] or list()",
    description: "Create list",
    platform: "All",
  },
  {
    id: "j34",
    app: "Python",
    category: "Basics",
    name: "Dict",
    keys: "{} or dict()",
    description: "Create dictionary",
    platform: "All",
  },
  {
    id: "j35",
    app: "Python",
    category: "Basics",
    name: "Tuple",
    keys: "() or tuple()",
    description: "Create tuple",
    platform: "All",
  },
  {
    id: "j36",
    app: "Python",
    category: "Basics",
    name: "Set",
    keys: "{} or set()",
    description: "Create set",
    platform: "All",
  },
  {
    id: "j37",
    app: "Python",
    category: "Basics",
    name: "String",
    keys: "'' or \"\"",
    description: "Create string",
    platform: "All",
  },
  {
    id: "j38",
    app: "Python",
    category: "Basics",
    name: "F-String",
    keys: "f'{var}'",
    description: "Format string",
    platform: "All",
  },
  {
    id: "j39",
    app: "Python",
    category: "Basics",
    name: "Type Check",
    keys: "type(var)",
    description: "Check variable type",
    platform: "All",
  },
  {
    id: "j40",
    app: "Python",
    category: "Basics",
    name: "Length",
    keys: "len(var)",
    description: "Get length",
    platform: "All",
  },

  {
    id: "j41",
    app: "Python",
    category: "Imports",
    name: "Import Module",
    keys: "import module",
    description: "Import module",
    platform: "All",
  },
  {
    id: "j42",
    app: "Python",
    category: "Imports",
    name: "From Import",
    keys: "from module import name",
    description: "Import specific item",
    platform: "All",
  },
  {
    id: "j43",
    app: "Python",
    category: "Imports",
    name: "Import As",
    keys: "import module as m",
    description: "Import with alias",
    platform: "All",
  },
  {
    id: "j44",
    app: "Python",
    category: "Imports",
    name: "NumPy",
    keys: "import numpy as np",
    description: "Import NumPy",
    platform: "All",
  },
  {
    id: "j45",
    app: "Python",
    category: "Imports",
    name: "Pandas",
    keys: "import pandas as pd",
    description: "Import Pandas",
    platform: "All",
  },
  {
    id: "j46",
    app: "Python",
    category: "Imports",
    name: "Matplotlib",
    keys: "import matplotlib.pyplot as plt",
    description: "Import Matplotlib",
    platform: "All",
  },
  {
    id: "j47",
    app: "Python",
    category: "Imports",
    name: "Scikit-learn",
    keys: "from sklearn import ...",
    description: "Import sklearn",
    platform: "All",
  },
  {
    id: "j48",
    app: "Python",
    category: "Imports",
    name: "Requests",
    keys: "import requests",
    description: "Import requests",
    platform: "All",
  },

  // ADOBE - 100+ Shortcuts (Photoshop focus)
  {
    id: "a1",
    app: "Adobe Photoshop",
    category: "File",
    name: "New",
    keys: "Ctrl + N",
    description: "Create new file",
    platform: "All",
  },
  {
    id: "a2",
    app: "Adobe Photoshop",
    category: "File",
    name: "Open",
    keys: "Ctrl + O",
    description: "Open file",
    platform: "All",
  },
  {
    id: "a3",
    app: "Adobe Photoshop",
    category: "File",
    name: "Open As",
    keys: "Ctrl + Alt + O",
    description: "Open as layers",
    platform: "All",
  },
  {
    id: "a4",
    app: "Adobe Photoshop",
    category: "File",
    name: "Save",
    keys: "Ctrl + S",
    description: "Save file",
    platform: "All",
  },
  {
    id: "a5",
    app: "Adobe Photoshop",
    category: "File",
    name: "Save As",
    keys: "Ctrl + Shift + S",
    description: "Save As dialog",
    platform: "All",
  },
  {
    id: "a6",
    app: "Adobe Photoshop",
    category: "File",
    name: "Export",
    keys: "Ctrl + Shift + Alt + S",
    description: "Export for web",
    platform: "All",
  },
  {
    id: "a7",
    app: "Adobe Photoshop",
    category: "File",
    name: "Print",
    keys: "Ctrl + P",
    description: "Print dialog",
    platform: "All",
  },
  {
    id: "a8",
    app: "Adobe Photoshop",
    category: "File",
    name: "Close",
    keys: "Ctrl + W",
    description: "Close image",
    platform: "All",
  },
  {
    id: "a9",
    app: "Adobe Photoshop",
    category: "File",
    name: "Exit",
    keys: "Ctrl + Q",
    description: "Quit Photoshop",
    platform: "All",
  },
  {
    id: "a10",
    app: "Adobe Photoshop",
    category: "File",
    name: "Place",
    keys: "Ctrl + Alt + Shift + P",
    description: "Place image",
    platform: "All",
  },

  {
    id: "a11",
    app: "Adobe Photoshop",
    category: "Edit",
    name: "Undo",
    keys: "Ctrl + Z",
    description: "Undo",
    platform: "All",
  },
  {
    id: "a12",
    app: "Adobe Photoshop",
    category: "Edit",
    name: "Redo",
    keys: "Ctrl + Y",
    description: "Redo",
    platform: "All",
  },
  {
    id: "a13",
    app: "Adobe Photoshop",
    category: "Edit",
    name: "Fade",
    keys: "Ctrl + Shift + F",
    description: "Fade last filter",
    platform: "All",
  },
  {
    id: "a14",
    app: "Adobe Photoshop",
    category: "Edit",
    name: "Cut",
    keys: "Ctrl + X",
    description: "Cut",
    platform: "All",
  },
  {
    id: "a15",
    app: "Adobe Photoshop",
    category: "Edit",
    name: "Copy",
    keys: "Ctrl + C",
    description: "Copy",
    platform: "All",
  },
  {
    id: "a16",
    app: "Adobe Photoshop",
    category: "Edit",
    name: "Copy Merged",
    keys: "Ctrl + Shift + C",
    description: "Copy merged",
    platform: "All",
  },
  {
    id: "a17",
    app: "Adobe Photoshop",
    category: "Edit",
    name: "Paste",
    keys: "Ctrl + V",
    description: "Paste",
    platform: "All",
  },
  {
    id: "a18",
    app: "Adobe Photoshop",
    category: "Edit",
    name: "Paste In Place",
    keys: "Ctrl + Alt + V",
    description: "Paste in place",
    platform: "All",
  },
  {
    id: "a19",
    app: "Adobe Photoshop",
    category: "Edit",
    name: "Fill",
    keys: "Ctrl + Alt + Backspace",
    description: "Fill foreground",
    platform: "All",
  },
  {
    id: "a20",
    app: "Adobe Photoshop",
    category: "Edit",
    name: "Fill Background",
    keys: "Ctrl + Backspace",
    description: "Fill background",
    platform: "All",
  },

  {
    id: "a21",
    app: "Adobe Photoshop",
    category: "Selection",
    name: "Select All",
    keys: "Ctrl + A",
    description: "Select all",
    platform: "All",
  },
  {
    id: "a22",
    app: "Adobe Photoshop",
    category: "Selection",
    name: "Deselect",
    keys: "Ctrl + D",
    description: "Deselect",
    platform: "All",
  },
  {
    id: "a23",
    app: "Adobe Photoshop",
    category: "Selection",
    name: "Reselect",
    keys: "Ctrl + Shift + D",
    description: "Reselect",
    platform: "All",
  },
  {
    id: "a24",
    app: "Adobe Photoshop",
    category: "Selection",
    name: "Invert",
    keys: "Ctrl + Shift + I",
    description: "Invert selection",
    platform: "All",
  },
  {
    id: "a25",
    app: "Adobe Photoshop",
    category: "Selection",
    name: "Feather",
    keys: "Ctrl + Alt + D",
    description: "Feather selection",
    platform: "All",
  },
  {
    id: "a26",
    app: "Adobe Photoshop",
    category: "Selection",
    name: "Refine",
    keys: "Ctrl + Alt + R",
    description: "Refine edge",
    platform: "All",
  },
  {
    id: "a27",
    app: "Adobe Photoshop",
    category: "Selection",
    name: "Modify Border",
    keys: "Ctrl + Alt + B",
    description: "Modify border",
    platform: "All",
  },
  {
    id: "a28",
    app: "Adobe Photoshop",
    category: "Selection",
    name: "Grow",
    keys: "Ctrl + Alt + G",
    description: "Grow selection",
    platform: "All",
  },
  {
    id: "a29",
    app: "Adobe Photoshop",
    category: "Selection",
    name: "Shrink",
    keys: "Ctrl + Alt + S",
    description: "Shrink selection",
    platform: "All",
  },
  {
    id: "a30",
    app: "Adobe Photoshop",
    category: "Selection",
    name: "By Color",
    keys: "Ctrl + Alt + Shift + A",
    description: "Select by color",
    platform: "All",
  },

  {
    id: "a31",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Rectangle Select",
    keys: "M",
    description: "Rectangle select tool",
    platform: "All",
  },
  {
    id: "a32",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Ellipse Select",
    keys: "E",
    description: "Ellipse select tool",
    platform: "All",
  },
  {
    id: "a33",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Free Select",
    keys: "L",
    description: "Lasso tool",
    platform: "All",
  },
  {
    id: "a34",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Magic Wand",
    keys: "W",
    description: "Magic wand tool",
    platform: "All",
  },
  {
    id: "a35",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Crop Tool",
    keys: "C",
    description: "Crop tool",
    platform: "All",
  },
  {
    id: "a36",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Slice Tool",
    keys: "K",
    description: "Slice tool",
    platform: "All",
  },
  {
    id: "a37",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Move Tool",
    keys: "V",
    description: "Move tool",
    platform: "All",
  },
  {
    id: "a38",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Zoom Tool",
    keys: "Z",
    description: "Zoom tool",
    platform: "All",
  },
  {
    id: "a39",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Hand Tool",
    keys: "Space",
    description: "Hand tool",
    platform: "All",
  },
  {
    id: "a40",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Paintbrush",
    keys: "B",
    description: "Paintbrush tool",
    platform: "All",
  },
  {
    id: "a41",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Pencil",
    keys: "N",
    description: "Pencil tool",
    platform: "All",
  },
  {
    id: "a42",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Eraser",
    keys: "E",
    description: "Eraser tool",
    platform: "All",
  },
  {
    id: "a43",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Clone",
    keys: "S",
    description: "Clone tool",
    platform: "All",
  },
  {
    id: "a44",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Dodge/Burn",
    keys: "O",
    description: "Dodge/Burn tool",
    platform: "All",
  },
  {
    id: "a45",
    app: "Adobe Photoshop",
    category: "Tools",
    name: "Type Tool",
    keys: "T",
    description: "Type tool",
    platform: "All",
  },

  {
    id: "a46",
    app: "Adobe Photoshop",
    category: "Image",
    name: "Image Size",
    keys: "Ctrl + Alt + I",
    description: "Image size dialog",
    platform: "All",
  },
  {
    id: "a47",
    app: "Adobe Photoshop",
    category: "Image",
    name: "Canvas Size",
    keys: "Ctrl + Alt + C",
    description: "Canvas size",
    platform: "All",
  },
  {
    id: "a48",
    app: "Adobe Photoshop",
    category: "Image",
    name: "Scale Image",
    keys: "Ctrl + Alt + Shift + I",
    description: "Scale image",
    platform: "All",
  },
  {
    id: "a49",
    app: "Adobe Photoshop",
    category: "Image",
    name: "Crop Image",
    keys: "Ctrl + Alt + Shift + C",
    description: "Crop to selection",
    platform: "All",
  },
  {
    id: "a50",
    app: "Adobe Photoshop",
    category: "Image",
    name: "Rotate 90 CW",
    keys: "Ctrl + Alt + R",
    description: "Rotate 90° CW",
    platform: "All",
  },

  {
    id: "a51",
    app: "Adobe Photoshop",
    category: "Layers",
    name: "New Layer",
    keys: "Ctrl + Shift + N",
    description: "Create new layer",
    platform: "All",
  },
  {
    id: "a52",
    app: "Adobe Photoshop",
    category: "Layers",
    name: "Duplicate Layer",
    keys: "Ctrl + J",
    description: "Duplicate layer",
    platform: "All",
  },
  {
    id: "a53",
    app: "Adobe Photoshop",
    category: "Layers",
    name: "Delete Layer",
    keys: "Ctrl + Alt + Shift + E",
    description: "Delete layer",
    platform: "All",
  },
  {
    id: "a54",
    app: "Adobe Photoshop",
    category: "Layers",
    name: "Merge Down",
    keys: "Ctrl + E",
    description: "Merge down",
    platform: "All",
  },
  {
    id: "a55",
    app: "Adobe Photoshop",
    category: "Layers",
    name: "Merge Visible",
    keys: "Ctrl + Shift + E",
    description: "Merge visible",
    platform: "All",
  },
  {
    id: "a56",
    app: "Adobe Photoshop",
    category: "Layers",
    name: "Flatten Image",
    keys: "Ctrl + Shift + Alt + E",
    description: "Flatten image",
    platform: "All",
  },
  {
    id: "a57",
    app: "Adobe Photoshop",
    category: "Layers",
    name: "Clipping Mask",
    keys: "Ctrl + Alt + G",
    description: "Create clipping mask",
    platform: "All",
  },
  {
    id: "a58",
    app: "Adobe Photoshop",
    category: "Layers",
    name: "Layer Mask",
    keys: "Ctrl + Alt + Shift + G",
    description: "Add layer mask",
    platform: "All",
  },
  {
    id: "a59",
    app: "Adobe Photoshop",
    category: "Layers",
    name: "Layer Style",
    keys: "Ctrl + Alt + Shift + L",
    description: "Layer style dialog",
    platform: "All",
  },
  {
    id: "a60",
    app: "Adobe Photoshop",
    category: "Layers",
    name: "Hide Layer",
    keys: "Ctrl + Alt + Shift + H",
    description: "Hide layer",
    platform: "All",
  },

  // MAC SHORTCUTS - Additional platform-specific
  {
    id: "m1",
    app: "Mac System",
    category: "Navigation",
    name: "Spotlight",
    keys: "Cmd + Space",
    description: "Open Spotlight search",
    platform: "Mac",
  },
  {
    id: "m2",
    app: "Mac System",
    category: "Navigation",
    name: "Command Tab",
    keys: "Cmd + Tab",
    description: "Switch applications",
    platform: "Mac",
  },
  {
    id: "m3",
    app: "Mac System",
    category: "Navigation",
    name: "Mission Control",
    keys: "F3",
    description: "Show all windows",
    platform: "Mac",
  },
  {
    id: "m4",
    app: "Mac System",
    category: "Navigation",
    name: "App Switcher",
    keys: "Cmd + Tab",
    description: "Switch between apps",
    platform: "Mac",
  },
  {
    id: "m5",
    app: "Mac System",
    category: "Navigation",
    name: "Quit App",
    keys: "Cmd + Q",
    description: "Quit application",
    platform: "Mac",
  },
  {
    id: "m6",
    app: "Mac System",
    category: "Navigation",
    name: "Hide App",
    keys: "Cmd + H",
    description: "Hide application",
    platform: "Mac",
  },
  {
    id: "m7",
    app: "Mac System",
    category: "Navigation",
    name: "Hide Others",
    keys: "Cmd + Alt + H",
    description: "Hide other apps",
    platform: "Mac",
  },
  {
    id: "m8",
    app: "Mac System",
    category: "Navigation",
    name: "Show Desktop",
    keys: "F11",
    description: "Show desktop",
    platform: "Mac",
  },
  {
    id: "m9",
    app: "Mac System",
    category: "Navigation",
    name: "Lock Screen",
    keys: "Ctrl + Cmd + Q",
    description: "Lock screen",
    platform: "Mac",
  },
  {
    id: "m10",
    app: "Mac System",
    category: "Navigation",
    name: "Restart",
    keys: "Ctrl + Cmd + Power",
    description: "Restart Mac",
    platform: "Mac",
  },

  // MORE DATA SCIENCE AND POWER BI
  {
    id: "ds1",
    app: "Power BI",
    category: "Navigation",
    name: "Home",
    keys: "Alt + H",
    description: "Go to home",
    platform: "All",
  },
  {
    id: "ds2",
    app: "Power BI",
    category: "Navigation",
    name: "Insert",
    keys: "Alt + I",
    description: "Insert visual",
    platform: "All",
  },
  {
    id: "ds3",
    app: "Power BI",
    category: "Navigation",
    name: "Modeling",
    keys: "Alt + O",
    description: "Go to modeling",
    platform: "All",
  },
  {
    id: "ds4",
    app: "Power BI",
    category: "Navigation",
    name: "View",
    keys: "Alt + V",
    description: "Go to view",
    platform: "All",
  },
  {
    id: "ds5",
    app: "Power BI",
    category: "Create",
    name: "New Report",
    keys: "Ctrl + N",
    description: "New report",
    platform: "All",
  },
  {
    id: "ds6",
    app: "Power BI",
    category: "Create",
    name: "New Dashboard",
    keys: "Ctrl + Alt + N",
    description: "New dashboard",
    platform: "All",
  },
  {
    id: "ds7",
    app: "Power BI",
    category: "Create",
    name: "Bar Chart",
    keys: "Alt + I + C",
    description: "Insert bar chart",
    platform: "All",
  },
  {
    id: "ds8",
    app: "Power BI",
    category: "Create",
    name: "Line Chart",
    keys: "Alt + I + L",
    description: "Insert line chart",
    platform: "All",
  },
  {
    id: "ds9",
    app: "Power BI",
    category: "Create",
    name: "Pie Chart",
    keys: "Alt + I + P",
    description: "Insert pie chart",
    platform: "All",
  },
  {
    id: "ds10",
    app: "Power BI",
    category: "Create",
    name: "Table",
    keys: "Alt + I + T",
    description: "Insert table",
    platform: "All",
  },
]

export const APPS = [
  "MS Word",
  "MS Excel",
  "VS Code",
  "Git",
  "Linux Terminal",
  "Jupyter Notebook",
  "Adobe Photoshop",
  "Mac System",
  "Power BI",
  "Python",
]

export const CATEGORIES = [
  "File",
  "Editing",
  "Navigation",
  "Formatting",
  "Formulas",
  "Tables",
  "Advanced",
  "Tools",
  "Layers",
  "Image",
  "Staging",
  "Commits",
  "Branches",
  "Remotes",
  "Permissions",
  "System",
  "Networking",
  "Package Manager",
  "Cells",
  "Kernel",
  "Basics",
  "Imports",
  "Selection",
  "Styles",
  "Create",
  "Modeling",
]
